// src/components/SeedDeportes.jsx
import { db } from '../firebaseConfig';
import { doc, setDoc } from 'firebase/firestore';

const chapters = [
  {
    id: 'cap1',
    title: 'Teoría del Entrenamiento',
    summary: 'El entrenamiento físico es un proceso sistemático donde el deportista se enfrenta a estímulos planificados denominados cargas, cuyo objetivo es provocar adaptaciones que mejoren su rendimiento. Estas cargas presentan una doble vertiente: la carga externa, constituida por las tareas y actividades físicas realizadas, y la carga interna o real, que representa el grado de esfuerzo y exigencia que dichas tareas imponen al organismo del individuo. Para que el organismo progrese, es fundamental romper el equilibrio interno o homeostasis mediante un estímulo adecuado, permitiendo que, tras un periodo de fatiga y recuperación, el cuerpo alcance un estado de capacidad superior conocido como supercompensación.',
    keyData: [
      'Carga externa vs. interna: la externa es la actividad propuesta; la interna es el efecto real en el cuerpo del deportista.',
      'Componentes de la carga: Volumen, frecuencia, intensidad, densidad y duración.',
      'Intensidad: indica el aspecto cualitativo; a mayor trabajo por unidad de tiempo, mayor intensidad.',
      'Densidad: es el cociente entre la duración del esfuerzo y la pausa de recuperación.',
      'Supercompensación: proceso biológico donde el organismo incrementa su capacidad funcional tras recuperarse de la fatiga.',
      'Metabolismo: se divide en Catabolismo (degradación para obtener energía) y Anabolismo (construcción y síntesis de tejidos).',
      'Progresión óptima: el orden recomendado para aumentar cargas es: 1. Volumen, 2. Intensidad, 3. Complejidad.',
      'Principio de Reversibilidad: las mejoras obtenidas se pierden si no se mantiene una actividad continuada.'
    ],
    practicalTips: 'En la vida cotidiana, al iniciar cualquier programa de ejercicio, es crucial evitar el error de "más es mejor". Aplicando el principio de individualización, no se debe copiar la rutina de otra persona, ya que cada organismo responde de manera distinta según su edad y condición previa. Para progresar de forma segura, se debe seguir la regla de la progresión: primero aumentar el volumen (ej. caminar 5 minutos más cada día) antes de intentar subir la intensidad (correr más rápido). Además, es vital respetar los días de descanso; entrenar intensamente sin pausas adecuadas impide la supercompensación, lo que puede generar agotamiento en lugar de mejora física.',
    order: 1
  },
  {
    id: 'cap2',
    title: 'La Fuerza',
    summary: 'La fuerza es considerada la capacidad física fundamental de la que dependen todas las demás manifestaciones del rendimiento. El documento establece que la fuerza máxima es el pilar central; si un atleta mejora su fuerza máxima, aumenta su reclutamiento de unidades motoras, lo que le permite desarrollar con mayor eficacia la fuerza-resistencia o la potencia. Se destaca que la fuerza no es solo una cuestión de tamaño muscular, sino que depende de factores neuronales (como la sincronización y el reclutamiento) y factores estructurales (como la hipertrofia).',
    keyData: [
      '1RM (Repetición Máxima): es el peso máximo que una persona puede levantar una sola vez. Se usa para calcular los porcentajes de intensidad del entrenamiento.',
      'Ley de Hill: describe la relación inversa entre la fuerza y la velocidad; a mayor carga, menor velocidad de ejecución.',
      'Hipertrofia Sarcoplasmática: aumento del volumen muscular por acumulación de glucógeno y agua, típica del entrenamiento con cargas intermedias (50-90% de 1RM).',
      'RFD (Rate of Force Development): velocidad con la que se produce la fuerza; fundamental para acciones explosivas.',
      'Frecuencia Cerebral: las fibras lentas requieren 15 Hz, las rápidas 30 Hz y las explosivas más de 45-100 Hz.'
    ],
    practicalTips: 'Si tu objetivo es ser más rápido y explosivo (ej. para artes marciales o sprints), no basta con "hacer pesas" para verte más grande. Debes incluir ejercicios con pesos altos pero pocas repeticiones para mejorar la conexión cerebro-músculo sin ganar peso innecesario que te vuelva lento. Además, es crucial realizar los movimientos con la intención de máxima velocidad, incluso si el peso es ligero, para enseñar a tu cerebro a reclutar las fibras explosivas que normalmente están "inhibidas".',
    order: 2
  },
  {
    id: 'cap3',
    title: 'Resistencia y Deporte Acíclico',
    summary: 'El documento plantea un cambio de paradigma: los deportes acíclicos (como fútbol, tenis o combate) no deben entrenarse igual que los cíclicos (maratón, natación). Mientras que en los cíclicos se busca mantener una "velocidad crucero", en los acíclicos la clave es la capacidad de acelerar y desacelerar repetidamente, lo que involucra un modelo bioquímico y biomecánico distinto. El método estrella para estos deportistas es el entrenamiento intermitente, que permite alcanzar altos niveles de consumo de oxígeno con menor fatiga residual comparado con los métodos tradicionales continuos.',
    keyData: [
      'Deporte Acíclico: aquel definido por la técnica, táctica y situaciones cambiantes, con miles de gestos de aceleración.',
      'Entrenamiento Intermitente: alternancia de esfuerzos muy cortos y pausas, ideal para quemar grasas y mejorar el VO2 máx.',
      'VAM: la velocidad mínima a la que se alcanza el consumo máximo de oxígeno (VO2 máx).',
      'Triada Fisiológica del Intermitente: alto consumo de oxígeno, consumo de grasas (lipólisis) y baja fatiga.',
      'Mioglobina: proteína que almacena oxígeno en el músculo y es vital en las pausas del ejercicio intermitente.'
    ],
    practicalTips: 'Si juegas deportes de equipo o practicas combate, no pierdas horas corriendo a ritmo lento en un parque. Es más efectivo realizar series intermitentes (ej. correr 15 segundos rápido y descansar 15 segundos caminando) durante 15 o 20 minutos. Esto mejora tu resistencia específica para el juego y, curiosamente, ayuda más a perder grasa corporal porque el aumento de citrato en la célula bloquea la quema de azúcar y obliga al cuerpo a usar grasas como combustible.',
    order: 3
  },
  {
    id: 'cap4',
    title: 'Flexibilidad, Valoración Funcional y Pliometría',
    summary: 'La flexibilidad se define como la capacidad física de amplitud de movimientos de una o varias articulaciones, sustentada en la movilidad articular y la elasticidad muscular. A diferencia de otras capacidades, la flexibilidad se manifiesta en todas las acciones humanas pero se pierde progresivamente con la edad, siendo más acentuada su reducción a partir de los 12 años debido a cambios hormonales. El documento enfatiza que una buena flexibilidad no solo mejora el rendimiento deportivo al permitir gestos técnicos más amplios, sino que es un pilar de la salud y la autonomía personal.',
    keyData: [
      'Flexibilidad: mayor en mujeres y alcanza su pico de efectividad en el entrenamiento entre los 10 y 14 años.',
      'FMS: un puntaje ≤ 14 indica 4 veces más riesgo de lesiones en miembros inferiores.',
      'Pliometría: el término fue introducido por Zaciorskiji en 1966.',
      'CEA Rápido: ocurre cuando el tiempo de transición es inferior a 200 milisegundos.',
      'Índice de Elasticidad: se calcula comparando la altura del salto con y sin contramovimiento ((CMJ-SJ)/SJ * 100).',
      'Reflejo Miotático: respuesta refleja que facilita la activación muscular tras un estiramiento brusco.'
    ],
    practicalTips: 'En tu rutina diaria, utiliza la sentadilla de evaluación frente a un espejo para observar si tus talones se elevan o si tus rodillas se inclinan hacia adentro (valgo). Si tus talones se levantan, es probable que tengas los músculos del sóleo tensos y necesites estirarlos. Al entrenar saltos (pliometría), asegúrate de que el contacto con el suelo sea breve; si pasas mucho tiempo "hundido" tras caer, la energía elástica se pierde en forma de calor y el ejercicio deja de ser efectivo para ganar potencia.',
    order: 4
  },
  {
    id: 'cap5',
    title: 'Metodología de los Ejercicios y Planificación ATR',
    summary: 'El entrenamiento deportivo se estructura mediante diferentes tipos de ejercicios: generales (buscan bases físicas ajenas al gesto competitivo), auxiliares, específicos (imitan el patrón de movimiento de la competición) y competitivos (la modalidad deportiva en sí). Se introduce el concepto de las "Familias de la Fuerza", que agrupan movimientos como empujes, tracciones y movimientos primarios, permitiendo una progresión desde ejercicios correctivos hasta la máxima carga funcional. La premisa fundamental es que se entrenan movimientos, no músculos aislados.',
    keyData: [
      'ATR: Acumulación, Transformación y Realización.',
      'Duración Mesociclo ATR: generalmente entre 14 y 28 días.',
      'Capacidades en ATR: se recomienda desarrollar solo 2 capacidades motoras y una técnica por mesociclo.',
      'Fuerza Útil: se produce a la velocidad y tiempo específicos del gesto de competición.',
      'Efecto Residual: tiempo que se mantienen las adaptaciones tras cesar el entrenamiento (máximo en fuerza aeróbica y mínima en velocidad).',
      'MMA: requiere fusionar técnicas de agarre (Lucha, Jiu-Jitsu) y golpeo (Boxeo, Muay Thai).'
    ],
    practicalTips: 'Si estás preparando un evento o competencia, no intentes mejorar todo a la vez (fuerza, velocidad y técnica) en la misma semana. Divide tu entrenamiento en bloques: dedica las primeras semanas a crear una base sólida de fuerza (Acumulación), luego enfócate en mover esos pesos lo más rápido posible (Transformación), y en las últimas dos semanas antes del evento, prioriza la velocidad y los gestos exactos de tu deporte (Realización). Recuerda: "No debes cargar una disfunción"; si te duele la espalda al hacer sentadillas, corrige tu postura antes de añadir más peso.',
    order: 5
  }
];

// Generar preguntas a partir del contenido (las 150 preguntas completas)
const questions = [
  // CAPÍTULO 1 (20 MC + 10 TF)
  { id: 'q1', chapterId: 'cap1', type: 'multiple-choice', question: '¿Cómo se denomina el grado de exigencia que representa el entrenamiento para el organismo?', options: ['Carga externa', 'Carga de mantenimiento', 'Carga interna', 'Carga inútil'], correct: 2, explanation: 'La carga interna es el esfuerzo real que el organismo realiza frente a una tarea.' },
  { id: 'q2', chapterId: 'cap1', type: 'multiple-choice', question: '¿Cuál es el componente que representa la medida cuantitativa de las cargas de entrenamiento?', options: ['Intensidad', 'Volumen', 'Densidad', 'Duración'], correct: 1, explanation: 'El volumen es la cantidad total de trabajo realizado.' },
  { id: 'q3', chapterId: 'cap1', type: 'multiple-choice', question: 'La potencia y especificidad del estímulo sobre el organismo es controlada por:', options: ['El volumen', 'La frecuencia', 'La intensidad', 'La densidad'], correct: 2, explanation: 'La intensidad controla la calidad y especificidad del esfuerzo.' },
  { id: 'q4', chapterId: 'cap1', type: 'multiple-choice', question: '¿Qué concepto define la relación entre la duración del esfuerzo y la pausa de recuperación?', options: ['Frecuencia', 'Densidad', 'Progresión', 'Continuidad'], correct: 1, explanation: 'La densidad es el cociente entre el tiempo de esfuerzo y el tiempo de pausa.' },
  { id: 'q5', chapterId: 'cap1', type: 'multiple-choice', question: '¿En qué orden se deben incrementar los parámetros para una progresión correcta?', options: ['Intensidad, Volumen, Complejidad', 'Complejidad, Volumen, Intensidad', 'Volumen, Intensidad, Complejidad', 'Volumen, Complejidad, Intensidad'], correct: 2, explanation: 'El orden recomendado es: 1. Volumen, 2. Intensidad, 3. Complejidad.' },
  { id: 'q6', chapterId: 'cap1', type: 'multiple-choice', question: '¿Qué ocurre si un estímulo de entrenamiento es de baja intensidad?', options: ['Provoca fatiga crónica', 'No provoca ninguna respuesta', 'Causa una supercompensación inmediata', 'Rompe drásticamente la homeostasis'], correct: 1, explanation: 'Un estímulo de baja intensidad no genera una respuesta adaptativa significativa.' },
  { id: 'q7', chapterId: 'cap1', type: 'multiple-choice', question: 'La fase del metabolismo que implica la degradación de moléculas para liberar energía es:', options: ['Anabolismo', 'Síntesis proteica', 'Homeostasis', 'Catabolismo'], correct: 3, explanation: 'El catabolismo es la fase de degradación que libera energía.' },
  { id: 'q8', chapterId: 'cap1', type: 'multiple-choice', question: 'El principio que establece que cada persona debe ser tratada según sus propias capacidades es:', options: ['Principio de totalidad', 'Principio de individualización', 'Principio de especialización', 'Principio de reversibilidad'], correct: 1, explanation: 'El principio de individualización reconoce que cada persona responde de forma única a los estímulos.' },
  { id: 'q9', chapterId: 'cap1', type: 'multiple-choice', question: 'El punto en el cual ya no se producen mejoras debido al estancamiento de las variables se llama:', options: ['Umbral', 'Shock', 'Meseta', 'Carga de recuperación'], correct: 2, explanation: 'La meseta es el estancamiento en el rendimiento por falta de variación de estímulos.' },
  { id: 'q10', chapterId: 'cap1', type: 'multiple-choice', question: 'El "Síndrome General de Adaptación" es la base biológica del entrenamiento y también se conoce como:', options: ['Ley de Selye', 'Teoría de Bompa', 'Principio de Navarro', 'Ley de Catabolismo'], correct: 0, explanation: 'El Síndrome General de Adaptación fue descrito por Hans Selye.' },
  { id: 'q11', chapterId: 'cap1', type: 'multiple-choice', question: '¿Qué sucede en la supercompensación nula?', options: ['El nivel funcional desciende por falta de descanso', 'El organismo asimila la actividad y mejora', 'Se repite el esfuerzo cuando los efectos del trabajo anterior han desaparecido', 'Se produce una fatiga crónica irreversible'], correct: 2, explanation: 'La supercompensación nula ocurre cuando el esfuerzo se repite sin que los efectos del trabajo anterior estén presentes.' },
  { id: 'q12', chapterId: 'cap1', type: 'multiple-choice', question: 'Cuando una actividad ajena a la especialidad mejora el rendimiento en esta última, hablamos de transferencia:', options: ['Negativa', 'Neutra', 'Indirecta', 'Positiva'], correct: 3, explanation: 'La transferencia positiva ocurre cuando una actividad ajena mejora el rendimiento en la especialidad.' },
  { id: 'q13', chapterId: 'cap1', type: 'multiple-choice', question: 'El entrenamiento que prioriza el trabajo general y polifacético en los primeros años de formación sigue el principio de:', options: ['Especialización', 'Multilateralidad', 'Reversibilidad', 'Continuidad'], correct: 1, explanation: 'La multilateralidad asegura una base física general antes de la especialización.' },
  { id: 'q14', chapterId: 'cap1', type: 'multiple-choice', question: '¿Cuál de estos NO es un componente de la magnitud de la carga?', options: ['Frecuencia', 'Duración', 'Entusiasmo', 'Volumen'], correct: 2, explanation: 'El entusiasmo no es un componente cuantificable de la carga de entrenamiento.' },
  { id: 'q15', chapterId: 'cap1', type: 'multiple-choice', question: 'El estado de equilibrio interno que el ejercicio busca romper se denomina:', options: ['Homeostasis', 'Catabolismo', 'Anabolismo', 'Supercompensación'], correct: 0, explanation: 'La homeostasis es el equilibrio interno que el ejercicio busca romper para generar adaptaciones.' },
  { id: 'q16', chapterId: 'cap1', type: 'multiple-choice', question: 'Si la carga de entrenamiento sobrepasa el nivel individual y agota las reservas de adaptación, el resultado será:', options: ['Óptimo', 'Inexistente', 'Negativo', 'De mantenimiento'], correct: 2, explanation: 'Una carga excesiva produce un resultado negativo, llevando al sobreentrenamiento.' },
  { id: 'q17', chapterId: 'cap1', type: 'multiple-choice', question: '¿Qué principio indica que los efectos del entrenamiento se pierden si no hay estimulación continuada?', options: ['Continuidad', 'Reversibilidad', 'Transferencia', 'Individualización'], correct: 1, explanation: 'El principio de reversibilidad establece que las adaptaciones se pierden si no se mantienen.' },
  { id: 'q18', chapterId: 'cap1', type: 'multiple-choice', question: 'Para evitar la monotonía y el estancamiento en el rendimiento, se debe aplicar el principio de:', options: ['Totalidad', 'Especialización', 'Alternancia', 'Especificidad'], correct: 0, explanation: 'El principio de totalidad aborda el entrenamiento como un proceso multifactorial y variado.' },
  { id: 'q19', chapterId: 'cap1', type: 'multiple-choice', question: 'El principio que dicta que la mejora es mayor cuando se realiza trabajo idéntico al gesto competitivo es:', options: ['Multilateralidad', 'Especificidad', 'Progresión', 'Individualización'], correct: 1, explanation: 'La especificidad indica que la mejora es mayor cuando el entrenamiento imita el gesto competitivo.' },
  { id: 'q20', chapterId: 'cap1', type: 'multiple-choice', question: 'En deportes dominados por el sistema muscular o cardiorrespiratorio, la madurez deportiva se alcanza:', options: ['En edades muy tempranas', 'Antes de los 15 años', 'Más tarde que en deportes de coordinación', 'Únicamente mediante entrenamiento de baja intensidad'], correct: 2, explanation: 'La madurez deportiva en estos deportes se alcanza más tarde debido a la complejidad fisiológica.' },
  { id: 'q21', chapterId: 'cap1', type: 'true-false', question: 'La carga externa se refiere al esfuerzo que el organismo realiza frente a una tarea.', correct: false, explanation: 'Esa es la carga interna. La carga externa es la actividad propuesta.' },
  { id: 'q22', chapterId: 'cap1', type: 'true-false', question: 'El anabolismo es el proceso constructivo donde la energía se usa para sintetizar moléculas complejas.', correct: true, explanation: 'El anabolismo es la fase constructiva del metabolismo.' },
  { id: 'q23', chapterId: 'cap1', type: 'true-false', question: 'La densidad indica la relación entre la duración del esfuerzo y la pausa de recuperación.', correct: true, explanation: 'La densidad es exactamente esa relación: esfuerzo vs. pausa.' },
  { id: 'q24', chapterId: 'cap1', type: 'true-false', question: 'La rutina de entrenamiento de un familiar siempre será beneficiosa para otra persona si tienen la misma edad.', correct: false, explanation: 'Cada persona requiere individualización según sus capacidades y condiciones.' },
  { id: 'q25', chapterId: 'cap1', type: 'true-false', question: 'Un estímulo constante de entrenamiento lleva inicialmente a una mejora, pero luego produce estancamiento.', correct: true, explanation: 'La falta de variación de estímulos produce una meseta en el rendimiento.' },
  { id: 'q26', chapterId: 'cap1', type: 'true-false', question: 'Los descansos largos son los más efectivos para lograr adaptaciones rápidas en el alto rendimiento.', correct: false, explanation: 'Los descansos largos no entrenan o producen supercompensación nula.' },
  { id: 'q27', chapterId: 'cap1', type: 'true-false', question: 'La transferencia neutra ocurre cuando los ejercicios realizados no mejoran ni empeoran la actividad principal.', correct: true, explanation: 'La transferencia neutra no tiene efecto positivo ni negativo sobre la actividad principal.' },
  { id: 'q28', chapterId: 'cap1', type: 'true-false', question: 'El principio de totalidad indica que el entrenamiento debe ser un proceso multifactorial con visión de conjunto.', correct: true, explanation: 'El principio de totalidad aborda el entrenamiento desde una perspectiva integradora.' },
  { id: 'q29', chapterId: 'cap1', type: 'true-false', question: 'El entrenamiento excesivo ocurre cuando el volumen o la intensidad se incrementan con demasiada rapidez.', correct: true, explanation: 'El aumento brusco de volumen o intensidad es una causa común de sobreentrenamiento.' },
  { id: 'q30', chapterId: 'cap1', type: 'true-false', question: 'La supercompensación negativa aparece cuando el esfuerzo se repite sin haber completado la fase de recuperación.', correct: true, explanation: 'La supercompensación negativa ocurre por falta de recuperación adecuada.' },

  // CAPÍTULO 2 (20 MC + 10 TF)
  { id: 'q31', chapterId: 'cap2', type: 'multiple-choice', question: '¿Cuál es la manifestación de fuerza que sirve de fuente a todas las demás?', options: ['Fuerza-resistencia', 'Fuerza-explosiva', 'Fuerza máxima', 'Fuerza técnica'], correct: 2, explanation: 'La fuerza máxima es la base de todas las demás manifestaciones de fuerza.' },
  { id: 'q32', chapterId: 'cap2', type: 'multiple-choice', question: '¿Qué ocurre con la velocidad de ejecución cuando disminuye la masa del objeto a lanzar?', options: ['Disminuye', 'Se mantiene igual', 'Aumenta', 'Se detiene'], correct: 2, explanation: 'Según la Ley de Hill, a menor carga, mayor velocidad de ejecución.' },
  { id: 'q33', chapterId: 'cap2', type: 'multiple-choice', question: 'El tiempo máximo aproximado que tarda en manifestarse completamente la fuerza máxima es de:', options: ['200 mseg', '500 mseg', '900 mseg', '1500 mseg'], correct: 2, explanation: 'La fuerza máxima tarda unos 900 milisegundos en manifestarse completamente.' },
  { id: 'q34', chapterId: 'cap2', type: 'multiple-choice', question: '¿Cuál de estos factores NO determina la fuerza máxima?', options: ['Calidad muscular', 'Color de la piel', 'Sistemas energéticos', 'Coordinación intramuscular'], correct: 1, explanation: 'El color de la piel no influye en la fuerza máxima.' },
  { id: 'q35', chapterId: 'cap2', type: 'multiple-choice', question: 'Las fibras musculares que tienen enorme resistencia a la fatiga son las:', options: ['Blancas explosivas', 'Blancas rápidas', 'Rojas lentas', 'Mixtas'], correct: 2, explanation: 'Las fibras rojas lentas son altamente resistentes a la fatiga.' },
  { id: 'q36', chapterId: 'cap2', type: 'multiple-choice', question: '¿Qué sistema energético predomina en las fibras explosivas (menos de 10 seg)?', options: ['Aeróbico', 'Anaeróbico láctico', 'Anaeróbico aláctico (ATP-PC)', 'Oxidativo'], correct: 2, explanation: 'Las fibras explosivas utilizan el sistema ATP-PC por ser de corta duración y alta intensidad.' },
  { id: 'q37', chapterId: 'cap2', type: 'multiple-choice', question: '¿Qué frecuencia de estímulo cerebral se requiere para activar las fibras lentas?', options: ['15 Hz', '30 Hz', '100 Hz', '200 Hz'], correct: 0, explanation: 'Las fibras lentas se activan con una frecuencia de aproximadamente 15 Hz.' },
  { id: 'q38', chapterId: 'cap2', type: 'multiple-choice', question: '¿Cómo se llama el proceso de ganar tamaño muscular por acumulación de glucógeno?', options: ['Hipertrofia miofibrilar', 'Hipertrofia sarcoplasmática', 'Atrofia selectiva', 'Sincronización'], correct: 1, explanation: 'La hipertrofia sarcoplasmática es el aumento de volumen por acumulación de glucógeno y agua.' },
  { id: 'q39', chapterId: 'cap2', type: 'multiple-choice', question: 'Una persona común suele utilizar solo este porcentaje de sus posibilidades musculares:', options: ['10%', '25%', '50%', '75%'], correct: 1, explanation: 'Una persona sedentaria utiliza aproximadamente el 25% de su capacidad muscular.' },
  { id: 'q40', chapterId: 'cap2', type: 'multiple-choice', question: 'El método óptimo para el desarrollo de la fuerza es el entrenamiento con:', options: ['Yoga', 'Sobrecarga (pesas)', 'Estiramientos', 'Resistencia continua'], correct: 1, explanation: 'El entrenamiento con sobrecarga (pesas) es el método más efectivo para desarrollar fuerza.' },
  { id: 'q41', chapterId: 'cap2', type: 'multiple-choice', question: '¿Qué es el 1RM?', options: ['Un minuto de descanso', 'Una repetición de mantenimiento', 'El peso máximo para una sola repetición', 'La resistencia muscular total'], correct: 2, explanation: '1RM es el peso máximo que se puede levantar en una sola repetición.' },
  { id: 'q42', chapterId: 'cap2', type: 'multiple-choice', question: 'Según la zona de intensidad, el entrenamiento de fuerza máxima requiere pesos de:', options: ['< 50% de 1RM', '50-75% de 1RM', '75-90% de 1RM', '90-100% de 1RM'], correct: 3, explanation: 'La fuerza máxima se entrena con cargas del 90-100% de 1RM.' },
  { id: 'q43', chapterId: 'cap2', type: 'multiple-choice', question: 'La "fuerza útil" se produce a:', options: ['Velocidad mínima', 'Velocidad y tiempo específicos del gesto de competición', 'Máximo volumen y baja intensidad', 'Durante el sueño profundo'], correct: 1, explanation: 'La fuerza útil se manifiesta a la velocidad y tiempo específicos del gesto deportivo.' },
  { id: 'q44', chapterId: 'cap2', type: 'multiple-choice', question: 'Para mejorar la coordinación neuromuscular se recomiendan cargas:', options: ['Muy ligeras (<20%)', 'Medias (50%)', 'Altas (≥85%)', 'Nulas'], correct: 2, explanation: 'Cargas altas (≥85% de 1RM) mejoran la coordinación neuromuscular.' },
  { id: 'q45', chapterId: 'cap2', type: 'multiple-choice', question: 'El RFD se refiere a la capacidad de:', options: ['Dormir mejor', 'Acelerar la propia masa corporal u objetos', 'Resistir una maratón', 'Ganar peso rápidamente'], correct: 1, explanation: 'El RFD (Rate of Force Development) es la capacidad de acelerar masa corporal u objetos.' },
  { id: 'q46', chapterId: 'cap2', type: 'multiple-choice', question: '¿Qué tipo de hipertrofia es causada por cargas del 50% al 85% de 1RM?', options: ['Hipertrofia con aumento de fuerza explosiva', 'Hipertrofia sarcoplasmática (estética)', 'Atrofia muscular', 'Hipertrofia de fibras lentas únicamente'], correct: 1, explanation: 'Las cargas del 50-85% de 1RM producen hipertrofia sarcoplasmática.' },
  { id: 'q47', chapterId: 'cap2', type: 'multiple-choice', question: 'En deportes de combate, trabajar solo fuerza máxima sin transferencia puede:', options: ['Ser inútil por el tiempo de aplicación real del impacto', 'Ganar la pelea automáticamente', 'Eliminar la necesidad de técnica', 'No cansar al atleta'], correct: 0, explanation: 'La fuerza máxima sin transferencia no es útil debido al corto tiempo de aplicación del impacto.' },
  { id: 'q48', chapterId: 'cap2', type: 'multiple-choice', question: 'Las fibras explosivas utilizan principalmente como combustible:', options: ['Grasas', 'Oxígeno', 'ATP y fosfocreatina', 'Ácido láctico'], correct: 2, explanation: 'Las fibras explosivas usan ATP y fosfocreatina como combustible principal.' },
  { id: 'q49', chapterId: 'cap2', type: 'multiple-choice', question: 'La inhibición neuromuscular del 75% restante en sedentarios se reduce mediante:', options: ['Masajes', 'Grandes pesos y altas velocidades', 'Dieta líquida', 'Descanso prolongado'], correct: 1, explanation: 'El entrenamiento con grandes pesos y altas velocidades reduce la inhibición neuromuscular.' },
  { id: 'q50', chapterId: 'cap2', type: 'multiple-choice', question: '¿Qué autor define la fuerza útil?', options: ['Selye', 'González Badillo', 'Bosco', 'Hill'], correct: 1, explanation: 'González Badillo es el autor que define el concepto de fuerza útil.' },
  { id: 'q51', chapterId: 'cap2', type: 'true-false', question: 'Las fibras rápidas tienen una enorme resistencia a la fatiga.', correct: false, explanation: 'Son las fibras lentas las que tienen enorme resistencia a la fatiga.' },
  { id: 'q52', chapterId: 'cap2', type: 'true-false', question: 'El entrenamiento con pesas siempre produce hipertrofia (crecimiento muscular).', correct: false, explanation: 'El entrenamiento con pesas puede mejorar el reclutamiento sin ganar masa muscular.' },
  { id: 'q53', chapterId: 'cap2', type: 'true-false', question: 'La intención de mover la carga rápido es tan importante como el peso mismo.', correct: true, explanation: 'La intención de velocidad es fundamental para reclutar fibras explosivas.' },
  { id: 'q54', chapterId: 'cap2', type: 'true-false', question: 'Un boxeador debe imitar gestos técnicos con poleas lentas para ser más explosivo.', correct: false, explanation: 'Las poleas lentas entrenan fibras rápidas de resistencia, no explosivas.' },
  { id: 'q55', chapterId: 'cap2', type: 'true-false', question: 'El 1RM se puede estimar mediante fórmulas si se hacen menos de 10 repeticiones al fallo.', correct: true, explanation: 'Existen fórmulas que estiman el 1RM a partir de repeticiones al fallo.' },
  { id: 'q56', chapterId: 'cap2', type: 'true-false', question: 'Las fibras explosivas se activan con estímulos cerebrales de baja frecuencia.', correct: false, explanation: 'Las fibras explosivas requieren alta frecuencia de estímulo cerebral.' },
  { id: 'q57', chapterId: 'cap2', type: 'true-false', question: 'La fuerza máxima dinámica es la base de las demás manifestaciones de fuerza.', correct: true, explanation: 'La fuerza máxima es la base de todas las demás manifestaciones de fuerza.' },
  { id: 'q58', chapterId: 'cap2', type: 'true-false', question: 'El glucógeno es el principal responsable de la hipertrofia sarcoplasmática.', correct: true, explanation: 'El glucógeno y el agua son los principales responsables de la hipertrofia sarcoplasmática.' },
  { id: 'q59', chapterId: 'cap2', type: 'true-false', question: 'Entrenar al fallo en cada serie es la mejor forma de ganar velocidad.', correct: false, explanation: 'Entrenar al fallo afecta negativamente la sincronización y la velocidad.' },
  { id: 'q60', chapterId: 'cap2', type: 'true-false', question: 'La fuerza útil es el objetivo principal del entrenamiento deportivo.', correct: true, explanation: 'La fuerza útil es el objetivo principal en el entrenamiento deportivo para mejorar el rendimiento.' },

  // CAPÍTULO 3 (20 MC + 10 TF)
  { id: 'q61', chapterId: 'cap3', type: 'multiple-choice', question: '¿Cuál es la característica principal de un deporte cíclico?', options: ['Momentos de situación permanentes', 'Esquema motor único y repetitivo', 'Incertidumbre técnica', 'No hay marcas de tiempo'], correct: 1, explanation: 'Los deportes cíclicos se caracterizan por un esquema motor repetitivo.' },
  { id: 'q62', chapterId: 'cap3', type: 'multiple-choice', question: 'En deportes acíclicos, ¿cuántos gestos de aceleración/desaceleración hay aproximadamente?', options: ['100', '500', '2000', '5000'], correct: 2, explanation: 'Los deportes acíclicos presentan alrededor de 2000 gestos de aceleración/desaceleración.' },
  { id: 'q63', chapterId: 'cap3', type: 'multiple-choice', question: '¿Qué método se considera el mejor para el desarrollo de capacidades en deportes acíclicos?', options: ['Carrera continua suave', 'Entrenamiento intermitente', 'Reposo absoluto', 'Estiramientos pasivos'], correct: 1, explanation: 'El entrenamiento intermitente es el más efectivo para deportes acíclicos.' },
  { id: 'q64', chapterId: 'cap3', type: 'multiple-choice', question: 'La sigla VAM significa:', options: ['Volumen Aeróbico Medio', 'Velocidad Aeróbica Máxima', 'Valor Atlético Muscular', 'Variación de Agilidad Máxima'], correct: 1, explanation: 'VAM significa Velocidad Aeróbica Máxima.' },
  { id: 'q65', chapterId: 'cap3', type: 'multiple-choice', question: '¿Cuál es el combustible principal en esfuerzos intermitentes de menos de 15 segundos?', options: ['Ácido láctico', 'Grasas únicamente', 'Fosfocreatina y ATP', 'Proteínas'], correct: 2, explanation: 'Los esfuerzos cortos utilizan fosfocreatina y ATP como combustible principal.' },
  { id: 'q66', chapterId: 'cap3', type: 'multiple-choice', question: '¿Qué molécula muscular almacena oxígeno y se recupera en las pausas breves?', options: ['Hemoglobina', 'Mioglobina', 'Insulina', 'Glucagón'], correct: 1, explanation: 'La mioglobina almacena oxígeno en el músculo y se recupera en las pausas.' },
  { id: 'q67', chapterId: 'cap3', type: 'multiple-choice', question: 'La triada fisiológica del ejercicio intermitente incluye bajo nivel de:', options: ['Consumo de oxígeno', 'Fatiga residual', 'Consumo de grasas', 'Frecuencia cardíaca'], correct: 1, explanation: 'El ejercicio intermitente produce baja fatiga residual.' },
  { id: 'q68', chapterId: 'cap3', type: 'multiple-choice', question: '¿Qué enzima es inhibida por el aumento de citrato, favoreciendo la lipólisis?', options: ['ATPasa', 'PFK (Fosfofructoquinasa)', 'Lactato deshidrogenasa', 'Amilasa'], correct: 1, explanation: 'El citrato inhibe la PFK, favoreciendo el uso de grasas como combustible.' },
  { id: 'q69', chapterId: 'cap3', type: 'multiple-choice', question: 'Un ejercicio intermitente metabólico común tiene una relación esfuerzo/pausa de:', options: ['15" x 15"', '5\' x 5\'', '1 hora x 10\'', '1" x 60"'], correct: 0, explanation: 'Un patrón común de ejercicio intermitente es 15 segundos de esfuerzo por 15 segundos de pausa.' },
  { id: 'q70', chapterId: 'cap3', type: 'multiple-choice', question: 'El reclutamiento de fibras rápidas en el intermitente depende de:', options: ['La velocidad crucero', 'La aceleración', 'La duración total del ejercicio', 'La altura del atleta'], correct: 1, explanation: 'La aceleración es el factor clave para el reclutamiento de fibras rápidas en el intermitente.' },
  { id: 'q71', chapterId: 'cap3', type: 'multiple-choice', question: '¿Qué test es útil para medir la VAM de forma progresiva e incremental?', options: ['Test de 1RM', 'Beep Test (shuttle run)', 'Test de flexibilidad', 'Evaluación de postura'], correct: 1, explanation: 'El Beep Test es un test incremental para medir la VAM.' },
  { id: 'q72', chapterId: 'cap3', type: 'multiple-choice', question: 'Según García Verdugo, el área aeróbica media se trabaja a este porcentaje de la VAM:', options: ['50%', '75%', '100%', '145%'], correct: 1, explanation: 'El área aeróbica media se trabaja al 75% de la VAM.' },
  { id: 'q73', chapterId: 'cap3', type: 'multiple-choice', question: 'El intermitente neuromuscular se basa en ejercicios de fuerza con cargas de:', options: ['10-20% RM', '40-60% RM', '90-100% RM', 'Sin carga'], correct: 1, explanation: 'El intermitente neuromuscular usa cargas del 40-60% de 1RM.' },
  { id: 'q74', chapterId: 'cap3', type: 'multiple-choice', question: 'En el entrenamiento intermitente, ¿qué sucede si el esfuerzo supera los 15-20 segundos?', options: ['Mejora la quema de grasa', 'Comienza el metabolismo láctico (ácido)', 'El atleta se duerme', 'No pasa nada'], correct: 1, explanation: 'Esfuerzos superiores a 15-20 segundos activan el metabolismo láctico.' },
  { id: 'q75', chapterId: 'cap3', type: 'multiple-choice', question: '¿Qué herramienta es muy útil para controlar la intensidad cuando no hay mucha experiencia?', options: ['El color de la camiseta', 'La frecuencia cardíaca', 'El tipo de calzado', 'La hora del día'], correct: 1, explanation: 'La frecuencia cardíaca es una herramienta útil para controlar la intensidad del entrenamiento.' },
  { id: 'q76', chapterId: 'cap3', type: 'multiple-choice', question: '¿Qué autor acuñó la "Paradoja Metabólica de la Fosfocreatina"?', options: ['Astrand', 'Selye', 'Argemi', 'Hill'], correct: 2, explanation: 'Argemi es el autor que acuñó el concepto de "Paradoja Metabólica de la Fosfocreatina".' },
  { id: 'q77', chapterId: 'cap3', type: 'multiple-choice', question: 'En la planificación de deportes acíclicos, se debe usar intensidad alta:', options: ['Solo al final de la temporada', 'Desde el comienzo de la temporada', 'Nunca', 'Solo en los días de lluvia'], correct: 1, explanation: 'En deportes acíclicos, se debe usar intensidad alta desde el comienzo de la temporada.' },
  { id: 'q78', chapterId: 'cap3', type: 'multiple-choice', question: 'El ejercicio intermitente metabólico-técnico NO debe superar la intensidad que el jugador puede resolver con su:', options: ['Fuerza máxima', 'Técnica', 'Dieta', 'Altura'], correct: 1, explanation: 'El ejercicio no debe superar la intensidad que el jugador pueda resolver con su técnica.' },
  { id: 'q79', chapterId: 'cap3', type: 'multiple-choice', question: 'Un test de 2000 metros para medir la VAM requiere dividir la distancia por el tiempo en:', options: ['Minutos', 'Segundos', 'Horas', 'Días'], correct: 1, explanation: 'El tiempo se mide en segundos para calcular la VAM en m/s.' },
  { id: 'q80', chapterId: 'cap3', type: 'multiple-choice', question: 'La lipólisis es el proceso de:', options: ['Degradación de proteínas', 'Utilización de grasas como energía', 'Formación de glucógeno', 'Producción de sudor'], correct: 1, explanation: 'La lipólisis es la utilización de grasas como fuente de energía.' },
  { id: 'q81', chapterId: 'cap3', type: 'true-false', question: 'Los deportes acíclicos se desenvuelven como una mezcla de corredor de fondo y velocista.', correct: true, explanation: 'Los deportes acíclicos combinan características de resistencia y velocidad.' },
  { id: 'q82', chapterId: 'cap3', type: 'true-false', question: 'El ejercicio intermitente es simplemente fraccionar una distancia larga en partes.', correct: false, explanation: 'El intermitente es un cambio de modelo bioenergético y biomecánico, no solo fraccionar distancias.' },
  { id: 'q83', chapterId: 'cap3', type: 'true-false', question: 'Las fibras lentas resintetizan ATP fuera de la mitocondria.', correct: false, explanation: 'Las fibras lentas resintetizan ATP dentro de la mitocondria por vía aeróbica.' },
  { id: 'q84', chapterId: 'cap3', type: 'true-false', question: 'El entrenamiento intermitente es menos eficiente que el continuo para mejorar el VO2 máx.', correct: false, explanation: 'El intermitente es muy eficiente para mejorar el VO2 máx y alcanza altos niveles de consumo de oxígeno.' },
  { id: 'q85', chapterId: 'cap3', type: 'true-false', question: 'El citrato inhibe la glucólisis, favoreciendo el uso de grasas.', correct: true, explanation: 'El citrato inhibe la PFK, bloqueando la glucólisis y favoreciendo la lipólisis.' },
  { id: 'q86', chapterId: 'cap3', type: 'true-false', question: 'En un deporte acíclico, el deportista sabe exactamente qué hará 5 segundos después.', correct: false, explanation: 'Los deportes acíclicos se caracterizan por la incertidumbre y situaciones cambiantes.' },
  { id: 'q87', chapterId: 'cap3', type: 'true-false', question: 'La VAM se puede expresar en km/h o m/s.', correct: true, explanation: 'La VAM se puede expresar en km/h o m/s según la conveniencia.' },
  { id: 'q88', chapterId: 'cap3', type: 'true-false', question: 'El entrenamiento interválico (intervalado) es igual al intermitente.', correct: false, explanation: 'El entrenamiento interválico suele ser de mayor duración y de tipo metabólico puro, a diferencia del intermitente.' },
  { id: 'q89', chapterId: 'cap3', type: 'true-false', question: 'Correr 10km en cinta es el mejor test para un jugador de fútbol.', correct: false, explanation: 'Para un jugador de fútbol se prefieren tests de campo específicos o intermitentes.' },
  { id: 'q90', chapterId: 'cap3', type: 'true-false', question: 'La fosfocreatina se recupera durante las pausas del ejercicio intermitente.', correct: true, explanation: 'La fosfocreatina se resintetiza durante las pausas del ejercicio intermitente.' },

  // CAPÍTULO 4 (20 MC + 10 TF)
  { id: 'q91', chapterId: 'cap4', type: 'multiple-choice', question: '¿A partir de qué edad la flexibilidad tiende a evolucionar de forma negativa?', options: ['5 años', '12 años', '25 años', '40 años'], correct: 1, explanation: 'La flexibilidad tiende a disminuir a partir de los 12 años debido a cambios hormonales.' },
  { id: 'q92', chapterId: 'cap4', type: 'multiple-choice', question: '¿Cuál es el puntaje de corte en el FMS que sugiere un riesgo elevado de lesión?', options: ['21', '18', '14', '10'], correct: 2, explanation: 'Un puntaje ≤ 14 en el FMS sugiere un riesgo elevado de lesión.' },
  { id: 'q93', chapterId: 'cap4', type: 'multiple-choice', question: 'El estiramiento que utiliza balanceos para forzar el cuerpo más allá de su ángulo normal es:', options: ['Estático', 'FNP', 'Isométrico', 'Balístico'], correct: 3, explanation: 'El estiramiento balístico utiliza balanceos para sobrepasar el ángulo normal.' },
  { id: 'q94', chapterId: 'cap4', type: 'multiple-choice', question: '¿Qué evalúa el Bastón por arriba de la cabeza en la sentadilla profunda?', options: ['La fuerza de bíceps', 'La estabilidad de la rodilla', 'La movilidad de hombros y espina torácica', 'El equilibrio de los pies'], correct: 2, explanation: 'El Bastón por arriba de la cabeza evalúa la movilidad de hombros y espina torácica.' },
  { id: 'q95', chapterId: 'cap4', type: 'multiple-choice', question: '¿Cómo se llama el ciclo que combina una contracción excéntrica seguida de una concéntrica?', options: ['Ciclo metabólico', 'Ciclo de estiramiento-acortamiento (CEA)', 'Ciclo de Krebs', 'Ciclo de recuperación nula'], correct: 1, explanation: 'El ciclo de estiramiento-acortamiento combina una contracción excéntrica seguida de una concéntrica.' },
  { id: 'q96', chapterId: 'cap4', type: 'multiple-choice', question: 'El test de salto que se realiza desde una posición de 90° sin rebote es:', options: ['Counter Movement Jump (CMJ)', 'Abalakov', 'Squat Jump (SJ)', 'Drop Jump (DJ)'], correct: 2, explanation: 'El Squat Jump se realiza desde una posición de 90° sin rebote.' },
  { id: 'q97', chapterId: 'cap4', type: 'multiple-choice', question: '¿Quién es considerado el padre de la pliometría aplicada al deporte?', options: ['Carmelo Bosco', 'Yuri Verkhoshansky', 'Gray Cook', 'Lev Matveev'], correct: 1, explanation: 'Yuri Verkhoshansky es considerado el padre de la pliometría aplicada al deporte.' },
  { id: 'q98', chapterId: 'cap4', type: 'multiple-choice', question: 'La "stiffness" o rigidez del sistema de impulsión se valora principalmente con el test de:', options: ['Flexibilidad activa', 'Sentadilla profunda', 'Reactividad o Drop Jump', 'Estiramiento FNP'], correct: 2, explanation: 'La rigidez del sistema de impulsión se valora con el test de reactividad o Drop Jump.' },
  { id: 'q99', chapterId: 'cap4', type: 'multiple-choice', question: '¿Cuál es el rango idóneo de estiramiento del músculo con respecto a su reposo para generar fuerza máxima?', options: ['50-60%', '110-120%', '200%', 'No debe estirarse nada'], correct: 1, explanation: 'El rango idóneo de estiramiento para generar fuerza máxima es 110-120% del reposo.' },
  { id: 'q100', chapterId: 'cap4', type: 'multiple-choice', question: 'El método FNP de estiramiento combina:', options: ['Saltos y carreras', 'Estiramiento pasivo y contracción isométrica', 'Pesas y natación', 'Frío y calor'], correct: 1, explanation: 'El método FNP combina estiramiento pasivo con contracción isométrica.' },
  { id: 'q101', chapterId: 'cap4', type: 'multiple-choice', question: '¿En qué momento del día suele registrarse la menor flexibilidad?', options: ['Al mediodía', 'A las 2 de la tarde', 'En las primeras horas de la mañana', 'Durante el sueño'], correct: 2, explanation: 'La menor flexibilidad suele registrarse en las primeras horas de la mañana.' },
  { id: 'q102', chapterId: 'cap4', type: 'multiple-choice', question: 'Una articulación con 3 grados de libertad permite:', options: ['Solo flexión y extensión', 'Flexión, extensión, rotación y circunducción', 'Solo torsión', 'Inmovilidad total'], correct: 1, explanation: 'Una articulación con 3 grados de libertad permite flexión, extensión, rotación y circunducción.' },
  { id: 'q103', chapterId: 'cap4', type: 'multiple-choice', question: 'El reflejo que protege la integridad muscular ante estiramientos excesivos es:', options: ['Reflejo miotático', 'Reflejo de Golgi', 'Reflejo de Babinski', 'Reflejo pupilar'], correct: 1, explanation: 'El reflejo de Golgi protege la integridad muscular ante estiramientos excesivos.' },
  { id: 'q104', chapterId: 'cap4', type: 'multiple-choice', question: 'En el test FMS, si un atleta siente dolor durante una prueba su puntaje es:', options: ['3', '2', '1', '0'], correct: 3, explanation: 'Si hay dolor, el puntaje en el test FMS es 0.' },
  { id: 'q105', chapterId: 'cap4', type: 'multiple-choice', question: 'El Squat Jump (SJ) mide principalmente:', options: ['La energía elástica', 'La capacidad contráctil y explosiva pura', 'La coordinación con brazos', 'La resistencia aeróbica'], correct: 1, explanation: 'El Squat Jump mide la capacidad contráctil y explosiva pura.' },
  { id: 'q106', chapterId: 'cap4', type: 'multiple-choice', question: '¿Qué altura de caída se utiliza habitualmente en el test de Drop Jump?', options: ['Solo 10 cm', 'Entre 20 cm y 100 cm', 'Más de 2 metros', 'Depende del peso del atleta únicamente'], correct: 1, explanation: 'En el Drop Jump se utilizan alturas de caída entre 20 cm y 100 cm.' },
  { id: 'q107', chapterId: 'cap4', type: 'multiple-choice', question: 'El uso de los brazos en el salto Abalakov permite:', options: ['Mayor coordinación y altura por transferencia de velocidad vertical', 'Menor fatiga', 'Evaluar solo la flexibilidad', 'Engañar el sensor de salto'], correct: 0, explanation: 'El uso de brazos en el salto Abalakov mejora la coordinación y altura del salto.' },
  { id: 'q108', chapterId: 'cap4', type: 'multiple-choice', question: '¿Qué significa ICC en el contexto de confiabilidad del FMS?', options: ['Índice de Carga Corporal', 'Coeficiente de Correlación Intraclase', 'Intensidad de Corriente Cerebral', 'Intervalo de Calidad Competitiva'], correct: 1, explanation: 'ICC significa Coeficiente de Correlación Intraclase en el contexto de confiabilidad del FMS.' },
  { id: 'q109', chapterId: 'cap4', type: 'multiple-choice', question: 'Un tiempo de contacto en el suelo superior a 200 ms en un Drop Jump indica:', options: ['Un salto perfecto', 'Pérdida de energía elástica en forma de calor', 'Que el atleta es muy fuerte', 'Un CEA rápido'], correct: 1, explanation: 'Un tiempo de contacto superior a 200 ms indica pérdida de energía elástica en forma de calor.' },
  { id: 'q110', chapterId: 'cap4', type: 'multiple-choice', question: 'La flexibilidad anatómica está determinada por:', options: ['La cantidad de agua ingerida', 'El grado de libertad natural de la articulación', 'El calzado deportivo', 'El estado de ánimo'], correct: 1, explanation: 'La flexibilidad anatómica está determinada por el grado de libertad natural de la articulación.' },
  { id: 'q111', chapterId: 'cap4', type: 'true-false', question: 'La flexibilidad aumenta gradualmente desde el nacimiento hasta la vejez.', correct: false, explanation: 'La flexibilidad disminuye gradualmente con la edad.' },
  { id: 'q112', chapterId: 'cap4', type: 'true-false', question: 'El estiramiento FNP es la forma más rápida de aumentar la flexibilidad estática-pasiva.', correct: true, explanation: 'El método FNP es una de las formas más rápidas de aumentar la flexibilidad.' },
  { id: 'q113', chapterId: 'cap4', type: 'true-false', question: 'En el test de sentadilla profunda, los pies deben apuntar hacia afuera en un ángulo de 45°.', correct: false, explanation: 'Los pies deben apuntar hacia adelante en el plano sagital.' },
  { id: 'q114', chapterId: 'cap4', type: 'true-false', question: 'El test de Bosco requiere plataformas de fuerza costosas para medir la altura del salto.', correct: false, explanation: 'Se puede usar una alfombra conductiva simple que mide el tiempo de vuelo.' },
  { id: 'q115', chapterId: 'cap4', type: 'true-false', question: 'Las mujeres son, en término medio, más flexibles que los varones a la misma edad.', correct: true, explanation: 'Las mujeres son, en promedio, más flexibles que los varones.' },
  { id: 'q116', chapterId: 'cap4', type: 'true-false', question: 'El CEA lento se caracteriza por no tener tiempo para lograr niveles altos de fuerza.', correct: false, explanation: 'En el CEA lento se tiene más tiempo y se genera alta tensión inicial.' },
  { id: 'q117', chapterId: 'cap4', type: 'true-false', question: 'El reflejo miotático se opone al estiramiento muscular facilitando la activación.', correct: true, explanation: 'El reflejo miotático facilita la activación muscular tras un estiramiento brusco.' },
  { id: 'q118', chapterId: 'cap4', type: 'true-false', question: 'Una rodilla en "valgo" significa que la rodilla se desplaza hacia afuera del pie.', correct: false, explanation: 'Una rodilla en valgo se desplaza hacia adentro del pie.' },
  { id: 'q119', chapterId: 'cap4', type: 'true-false', question: 'El test Abalakov es prácticamente igual al CMJ pero permite el uso de brazos.', correct: true, explanation: 'El Abalakov es similar al CMJ pero permite el uso de brazos.' },
  { id: 'q120', chapterId: 'cap4', type: 'true-false', question: 'La flexibilidad excesiva siempre es beneficiosa y nunca predispone a lesiones.', correct: false, explanation: 'La flexibilidad excesiva puede ir en detrimento de la estabilidad y causar lesiones.' },

  // CAPÍTULO 5 (20 MC + 10 TF)
  { id: 'q121', chapterId: 'cap5', type: 'multiple-choice', question: '¿Qué tipo de ejercicio imita el patrón de movimiento de la competición?', options: ['General', 'Auxiliar', 'Específico', 'Correctivo'], correct: 2, explanation: 'El ejercicio específico imita el patrón de movimiento de la competición.' },
  { id: 'q122', chapterId: 'cap5', type: 'multiple-choice', question: 'El modelo ATR se caracteriza por:', options: ['Desarrollo simultáneo de 10 capacidades', 'Concentración de cargas en pocas capacidades', 'No tener descansos', 'Ser solo para principiantes'], correct: 1, explanation: 'El modelo ATR concentra las cargas en pocas capacidades para optimizar el entrenamiento.' },
  { id: 'q123', chapterId: 'cap5', type: 'multiple-choice', question: '¿Cuál es el objetivo principal del mesociclo de Acumulación?', options: ['Modelación competitiva', 'Aumentar el potencial motor y bases físicas', 'Perder peso rápidamente', 'Entrenar solo la velocidad'], correct: 1, explanation: 'El mesociclo de Acumulación busca aumentar el potencial motor y las bases físicas.' },
  { id: 'q124', chapterId: 'cap5', type: 'multiple-choice', question: 'En el modelo ATR, ¿qué mesociclo precede inmediatamente a la competición?', options: ['Acumulación', 'Transformación', 'Realización', 'Transición'], correct: 2, explanation: 'El mesociclo de Realización precede inmediatamente a la competición.' },
  { id: 'q125', chapterId: 'cap5', type: 'multiple-choice', question: '¿Quién planteó la frase "Entrenamos movimientos y no músculos"?', options: ['Vern Gambetta', 'Lev Matveev', 'Bosco', 'Selye'], correct: 0, explanation: 'Vern Gambetta es el autor de la frase "Entrenamos movimientos y no músculos".' },
  { id: 'q126', chapterId: 'cap5', type: 'multiple-choice', question: 'El "Cerebro Reptiliano" regula funciones como:', options: ['El habla y el lenguaje', 'La temperatura, respiración y reflejos', 'La memoria a largo plazo', 'El pensamiento matemático'], correct: 1, explanation: 'El "Cerebro Reptiliano" regula funciones básicas como temperatura, respiración y reflejos.' },
  { id: 'q127', chapterId: 'cap5', type: 'multiple-choice', question: '¿Qué capacidad tiene el mayor efecto residual (dura más tiempo)?', options: ['Velocidad máxima', 'Resistencia aeróbica y Fuerza máxima', 'Potencia anaeróbica aláctica', 'Flexibilidad del hombro'], correct: 1, explanation: 'La resistencia aeróbica y la fuerza máxima tienen el mayor efecto residual.' },
  { id: 'q128', chapterId: 'cap5', type: 'multiple-choice', question: 'Un ejercicio de natación usado como recuperación para un ciclista es un:', options: ['Ejercicio específico', 'Ejercicio general no orientado', 'Ejercicio competitivo', 'Ejercicio de fuerza máxima'], correct: 1, explanation: 'La natación como recuperación para un ciclista es un ejercicio general no orientado.' },
  { id: 'q129', chapterId: 'cap5', type: 'multiple-choice', question: '¿Cuál es la proporción recomendada de cargas generales vs. específicas al final de una preparación de MMA?', options: ['90% General / 10% Específico', '50% General / 50% Específico', '10% General / 90% Específico', '100% General'], correct: 2, explanation: 'Al final de una preparación de MMA se recomienda 10% de cargas generales y 90% de cargas específicas.' },
  { id: 'q130', chapterId: 'cap5', type: 'multiple-choice', question: 'El método de "contraste" en el mesociclo de transformación combina:', options: ['Pesas pesadas y ligeras seguidas', 'Correr y nadar', 'Ayuno y dieta', 'Dormir y entrenar'], correct: 0, explanation: 'El método de contraste combina pesas pesadas y ligeras en la misma sesión.' },
  { id: 'q131', chapterId: 'cap5', type: 'multiple-choice', question: '¿Qué autor es el principal referente del diseño convencional de periodización?', options: ['Fernando Navarro', 'Lev Matveev', 'Gray Cook', 'Rodrigo Merlo'], correct: 1, explanation: 'Lev Matveev es el principal referente del diseño convencional de periodización.' },
  { id: 'q132', chapterId: 'cap5', type: 'multiple-choice', question: '¿Qué nombre recibe la unidad de entrenamiento similar al ciclo anual pero en miniatura?', options: ['Microciclo', 'Macrociclo ATR', 'Sesión', 'Tarea'], correct: 1, explanation: 'El Macrociclo ATR es similar al ciclo anual pero en miniatura.' },
  { id: 'q133', chapterId: 'cap5', type: 'multiple-choice', question: 'El mesociclo de Transformación busca convertir el potencial acumulado en:', options: ['Grasa corporal', 'Preparación especial y potencia', 'Cansancio crónico', 'Masa muscular únicamente'], correct: 1, explanation: 'El mesociclo de Transformación convierte el potencial acumulado en preparación especial y potencia.' },
  { id: 'q134', chapterId: 'cap5', type: 'multiple-choice', question: 'En deportes de combate, ¿qué grupo muscular debe trabajarse a diario?', options: ['Bíceps', 'Core, prensores y cuello', 'Gemelos únicamente', 'Ninguno, se debe descansar siempre'], correct: 1, explanation: 'En deportes de combate, el core, prensores y cuello deben trabajarse a diario.' },
  { id: 'q135', chapterId: 'cap5', type: 'multiple-choice', question: 'Según la "Familia de los Empujes de Brazos", el press de banca es:', options: ['Un ejercicio correctivo', 'Un máximo representante de fuerza', 'Un ejercicio de tracción', 'Prohibido en deportistas'], correct: 1, explanation: 'El press de banca es un máximo representante de fuerza dentro de la "Familia de los Empujes de Brazos".' },
  { id: 'q136', chapterId: 'cap5', type: 'multiple-choice', question: '¿Qué porcentaje del trabajo total en un mesociclo ATR debe dirigirse a las capacidades motoras principales?', options: ['10%', '30%', '50%', '70-80%'], correct: 3, explanation: 'En un mesociclo ATR, el 70-80% del trabajo total debe dirigirse a las capacidades motoras principales.' },
  { id: 'q137', chapterId: 'cap5', type: 'multiple-choice', question: 'La "triple extensión" en el movimiento humano involucra:', options: ['Mano, codo y hombro', 'Tobillo, rodilla y cadera', 'Cabeza, cuello y tronco', 'Dedos, muñeca y antebrazo'], correct: 1, explanation: 'La triple extensión involucra tobillo, rodilla y cadera.' },
  { id: 'q138', chapterId: 'cap5', type: 'multiple-choice', question: '¿Cuál es un inconveniente del diseño convencional para atletas de élite?', options: ['Es demasiado corto', 'No permite alcanzar varios picos de forma al año', 'Solo entrena una capacidad', 'Es muy divertido'], correct: 1, explanation: 'El diseño convencional no permite alcanzar varios picos de forma al año, limitando a los atletas de élite.' },
  { id: 'q139', chapterId: 'cap5', type: 'multiple-choice', question: 'El entrenamiento de fuerza máxima en el periodo de acumulación de combate usa:', options: ['10-20% de 1RM', '30-65% de 1RM', '80-100% de 1RM', 'Pesos imaginarios'], correct: 2, explanation: 'En el periodo de acumulación de combate, la fuerza máxima se entrena con cargas del 80-100% de 1RM.' },
  { id: 'q140', chapterId: 'cap5', type: 'multiple-choice', question: 'Los ejercicios "Anti-rotación" sirven para:', options: ['Marearse más', 'Conexión estructural y estabilidad del Core', 'Ganar flexibilidad de dedos', 'No sirven para nada'], correct: 1, explanation: 'Los ejercicios anti-rotación mejoran la conexión estructural y estabilidad del Core.' },
  { id: 'q141', chapterId: 'cap5', type: 'true-false', question: 'El modelo ATR renuncia al entrenamiento simultáneo de muchas capacidades.', correct: true, explanation: 'El modelo ATR se basa en la concentración de cargas en pocas capacidades.' },
  { id: 'q142', chapterId: 'cap5', type: 'true-false', question: 'Los ejercicios auxiliares son idénticos a los de competición.', correct: false, explanation: 'Los ejercicios auxiliares no son idénticos a los de competición; los competitivos o específicos sí lo son.' },
  { id: 'q143', chapterId: 'cap5', type: 'true-false', question: 'En el periodo de realización se debe entrenar en un estado bien descansado.', correct: true, explanation: 'En el periodo de realización se debe entrenar en un estado bien descansado para optimizar el rendimiento.' },
  { id: 'q144', chapterId: 'cap5', type: 'true-false', question: 'La fuerza potencia se trabaja con cargas entre el 55% y 80% de 1RM.', correct: true, explanation: 'La fuerza potencia se entrena con cargas del 55-80% de 1RM.' },
  { id: 'q145', chapterId: 'cap5', type: 'true-false', question: 'El entrenamiento convencional de Matveev es el más recomendado para deportistas de alto nivel actual.', correct: false, explanation: 'Actualmente se prefiere el modelo ATR por la concentración de cargas.' },
  { id: 'q146', chapterId: 'cap5', type: 'true-false', question: '"Mover peso" es siempre más importante que la calidad del movimiento.', correct: false, explanation: 'La calidad del movimiento debe preceder a la carga para evitar lesiones.' },
  { id: 'q147', chapterId: 'cap5', type: 'true-false', question: 'El mesociclo de realización incluye la modelación de la actividad competitiva.', correct: true, explanation: 'El mesociclo de realización incluye la modelación de la actividad competitiva.' },
  { id: 'q148', chapterId: 'cap5', type: 'true-false', question: 'En MMA, los sparrings predominan en las últimas 3-4 semanas antes de la pelea.', correct: true, explanation: 'Los sparrings predominan en las últimas 3-4 semanas antes de una pelea de MMA.' },
  { id: 'q149', chapterId: 'cap5', type: 'true-false', question: 'El efecto residual de la velocidad máxima es muy largo (varios meses).', correct: false, explanation: 'El efecto residual de la velocidad máxima es uno de los más cortos.' },
  { id: 'q150', chapterId: 'cap5', type: 'true-false', question: 'La individualización es un requisito clave para el éxito del modelo ATR.', correct: true, explanation: 'La individualización es clave para el éxito del modelo ATR.' }
];

export default function SeedDeportes() {
  const handleSeed = async () => {
    try {
      for (const ch of chapters) {
        await setDoc(doc(db, 'deportes', ch.id), ch);
        console.log(`✅ Capítulo: ${ch.title}`);
      }
      for (const q of questions) {
        await setDoc(doc(db, 'deportesTrivia', q.id), q);
      }
      alert('🎉 Datos de Deportes subidos correctamente.');
    } catch (error) {
      console.error('❌ Error:', error);
      alert('❌ Error al subir datos. Revisa la consola.');
    }
  };

  return (
    <button
      onClick={handleSeed}
      style={{
        padding: '12px 24px',
        background: '#6C63FF',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '1rem',
        marginBottom: '20px'
      }}
    >
      ⚽ Subir datos de Deportes
    </button>
  );
}