// src/components/SeedNeuro.jsx
import { db } from '../firebaseConfig';
import { doc, setDoc } from 'firebase/firestore';

// ============================================================
// CAPÍTULOS (5)
// ============================================================
const modules = [
  {
    id: 'module1',
    title: 'La célula que piensa',
    icon: '🧠',
    description: 'Neuronas, sinapsis y neurotransmisores',
    order: 1,
    summary: 'Tu cerebro tiene alrededor de 86 mil millones de neuronas, y ninguna de ellas piensa sola. Una neurona es una célula especializada en recibir y enviar información. Tiene tres partes clave: las dendritas (reciben mensajes de otras neuronas), el cuerpo celular o soma (procesa esa información), y el axón (envía el mensaje hacia adelante, como un cable). Cuando una neurona "dispara", genera un impulso eléctrico que viaja por el axón hasta el final, donde no toca directamente a la siguiente neurona — hay un pequeño espacio llamado sinapsis. Ahí, el impulso eléctrico se convierte en un mensaje químico: se liberan neurotransmisores, moléculas que cruzan ese espacio y le "hablan" a la neurona siguiente. Todo lo que sientes, piensas o haces es, en el fondo, este proceso repitiéndose millones de veces por segundo entre neuronas conectadas en red.',
    keyData: [
      'Una neurona típica se conecta con miles de otras neuronas a través de sus dendritas.',
      'El impulso eléctrico dentro de la neurona se llama potencial de acción.',
      'Los neurotransmisores más conocidos son la dopamina (motivación/recompensa), la serotonina (estado de ánimo) y el GABA (calma/inhibición).',
      'La sinapsis no es un contacto físico directo: es un espacio microscópico que el mensaje químico debe cruzar.',
      'Ninguna neurona "piensa" por sí sola — un pensamiento o una emoción es la actividad coordinada de redes enteras de neuronas.'
    ],
    practicalTips: 'Cuando en la app leas sobre "cambiar hábitos" o "calmar la mente", en el fondo estás hablando de este nivel: activar ciertas redes de neuronas una y otra vez. Entender esto te prepara para el Capítulo 3 (neuroplasticidad), donde vas a ver que estas conexiones no son fijas — se fortalecen o debilitan según lo que practiques.'
  },
  {
    id: 'module2',
    title: 'El mapa del cerebro',
    icon: '🗺️',
    description: 'Corteza prefrontal, amígdala, hipocampo, ínsula y más',
    order: 2,
    summary: 'El cerebro no es una masa uniforme: distintas zonas se especializan en distintas funciones, aunque trabajan en conjunto. La corteza prefrontal, ubicada justo detrás de la frente, es la responsable de tomar decisiones, planificar y frenar impulsos — es la parte más "madura" y lenta en desarrollarse. La amígdala, pequeña y en forma de almendra, funciona como sistema de alarma: detecta amenazas y dispara miedo o ansiedad antes de que puedas pensarlo conscientemente. El hipocampo es el archivo de la memoria: convierte experiencias en recuerdos que puedes recuperar después. La ínsula, escondida en un pliegue profundo del cerebro, recibe las señales del cuerpo (latidos, respiración, tensión muscular) y te permite sentir lo que ocurre por dentro. Finalmente, el cerebelo y el tronco encefálico manejan funciones automáticas: equilibrio, coordinación motora, respiración, ritmo cardíaco — todo sin que tengas que pensarlo.',
    keyData: [
      'La corteza prefrontal es la última zona del cerebro en terminar de desarrollarse (hasta mediados de los 20 años).',
      'La amígdala puede activarse en milisegundos, antes de que la corteza prefrontal "se entere" — por eso a veces reaccionas con miedo antes de razonar.',
      'El hipocampo es especialmente vulnerable al estrés crónico: el cortisol sostenido puede dañarlo.',
      'La ínsula es clave en la interocepción: la capacidad de sentir el estado interno de tu propio cuerpo.',
      'Ninguna de estas áreas trabaja aislada — funcionan como una red interconectada, no como compartimentos separados.'
    ],
    practicalTips: 'Cuando entiendas por qué "sientes" antes de "pensar" (amígdala más rápida que corteza prefrontal), vas a comprender mejor tus propias reacciones emocionales. Este mapa de áreas es el vocabulario que vas a usar en todos los capítulos siguientes: neuroplasticidad (Cap. 3), cuerpo-cerebro (Cap. 4) y meditación (Cap. 5) hablan constantemente de amígdala, corteza prefrontal e ínsula.'
  },
  {
    id: 'module3',
    title: 'Un cerebro que cambia (neuroplasticidad)',
    icon: '🔄',
    description: 'El cerebro se reorganiza con la experiencia repetida',
    order: 3,
    summary: 'Durante mucho tiempo se pensó que el cerebro adulto era fijo, incapaz de cambiar. Hoy sabemos que eso es falso: el cerebro se reorganiza físicamente en respuesta a lo que haces, piensas y practicas. Esto se llama neuroplasticidad. Cuando repites una actividad — aprender un idioma, practicar un deporte, meditar — las conexiones entre las neuronas involucradas se fortalecen (recuerda el Capítulo 1: sinapsis). Con suficiente repetición, esas conexiones se vuelven más eficientes y hasta pueden generar cambios estructurales visibles, como el engrosamiento de ciertas áreas. Un ejemplo clásico: un estudio con taxistas de Londres mostró que su hipocampo (la zona de la memoria, Capítulo 2) era más grande de lo normal, probablemente por memorizar miles de calles durante años. La neuroplasticidad es la razón científica por la que un hábito nuevo, sostenido en el tiempo, puede literalmente cambiar tu cerebro.',
    keyData: [
      'La neuroplasticidad ocurre durante toda la vida, no solo en la infancia (aunque es más intensa en edades tempranas).',
      'El principio "úsalo o piérdelo" resume bien el concepto: las conexiones que no se usan tienden a debilitarse.',
      'El estudio de los taxistas de Londres (Maguire et al., 2000) es una de las evidencias más citadas de plasticidad estructural en adultos.',
      'La repetición constante, no la intensidad puntual, es lo que genera cambios duraderos.',
      'La neuroplasticidad es la base científica que explica por qué prácticas como la meditación pueden modificar el cerebro con el tiempo (esto se retoma en el Capítulo 5).'
    ],
    practicalTips: 'Ahora que entiendes que el cerebro cambia con la práctica repetida, el Capítulo 4 (cuerpo-cerebro) y el Capítulo 5 (meditación) van a tener sentido no como "magia" sino como consecuencia lógica: practicar atención plena de forma sostenida cambia físicamente las áreas involucradas, igual que memorizar calles cambió el hipocampo de los taxistas.'
  },
  {
    id: 'module4',
    title: 'El cerebro no está solo (cuerpo-cerebro)',
    icon: '🫀',
    description: 'Interocepción, respiración, corazón e intestino',
    order: 4,
    summary: 'El cerebro no funciona de manera aislada dentro del cráneo: está en constante comunicación con el resto del cuerpo. La interocepción es la capacidad de percibir señales internas — latidos del corazón, tensión muscular, sensación de hambre — y depende principalmente de la ínsula (Capítulo 2). La respiración es un ejemplo notable: el simple acto de respirar por la nariz influye en la actividad de zonas cerebrales relacionadas con la memoria y la emoción, y por eso técnicas de respiración consciente pueden modular tu estado mental. El corazón también "conversa" con el cerebro: el patrón de tus latidos (no solo la frecuencia, sino su variabilidad) se relaciona con cómo procesas emociones. Finalmente, el intestino alberga billones de microorganismos (la microbiota) que se comunican con el cerebro a través del sistema nervioso y sustancias químicas — el llamado eje intestino-cerebro —, influyendo incluso en el estado de ánimo.',
    keyData: [
      'La ínsula es la estructura cerebral central en el procesamiento de señales corporales internas (interocepción).',
      'La forma de respirar (ritmo, profundidad, vía nasal) afecta directamente la actividad de circuitos cerebrales de memoria y emoción.',
      'La variabilidad del latido cardíaco (no solo el pulso) es un indicador relevante del estado del sistema nervioso.',
      'El eje intestino-cerebro es una vía de comunicación bidireccional: el cerebro influye en el intestino, y el intestino influye en el cerebro.',
      'Esta comunicación cuerpo-cerebro es la base científica detrás de por qué técnicas como la respiración consciente o el trabajo corporal tienen efectos medibles en el estado mental.'
    ],
    practicalTips: 'Cuando en la app se hable de "respiración consciente" o "escuchar al cuerpo", ahora sabes que no es una frase motivacional vacía: hay una vía biológica real (ínsula, nervio vago, eje intestino-cerebro) detrás de esas prácticas. Esto conecta directamente con el Capítulo 5, donde vas a ver que gran parte de lo que hace la meditación es, justamente, entrenar esta comunicación cuerpo-cerebro.'
  },
  {
    id: 'module5',
    title: 'Qué le pasa al cerebro cuando meditas',
    icon: '🧘',
    description: 'Atención, amígdala y sincronía cerebral',
    order: 5,
    summary: 'Con todo lo anterior — neuronas y sinapsis (Cap. 1), áreas del cerebro (Cap. 2), neuroplasticidad (Cap. 3) y comunicación cuerpo-cerebro (Cap. 4) — ya puedes entender qué ocurre realmente cuando alguien medita de forma sostenida. Estudios con meditadores de larga trayectoria muestran que la práctica repetida de atención plena se asocia con menor activación de la amígdala (el sistema de alarma, Cap. 2) ante estímulos emocionales negativos, y con una mayor eficiencia de los circuitos atencionales — es decir, se necesita menos esfuerzo para mantener la atención con la práctica. Investigaciones con electroencefalografía en meditadores expertos también han registrado patrones de actividad eléctrica sincronizada (ondas gamma) durante la práctica, algo poco común en personas sin entrenamiento. Todo esto es consistente con lo visto en el Capítulo 3: la meditación es, ante todo, una forma de entrenamiento mental que —como cualquier práctica repetida— puede generar cambios medibles en el cerebro con el tiempo, no un efecto mágico o inmediato.',
    keyData: [
      'La práctica sostenida de meditación se asocia con menor reactividad de la amígdala ante estímulos emocionales negativos.',
      'Meditadores con más horas de práctica muestran, en algunos estudios, mayor eficiencia atencional (logran el mismo resultado con menos esfuerzo cerebral).',
      'Se han registrado patrones de sincronía gamma inusualmente altos en meditadores de larga trayectoria durante la práctica.',
      'Estos hallazgos provienen principalmente de investigación con meditadores budistas experimentados, en colaboración entre neurocientíficos y practicantes contemplativos.',
      'La meditación, desde esta perspectiva, no es un fenómeno "místico" sino una forma de entrenamiento mental sujeta a los mismos principios de neuroplasticidad vistos en el Capítulo 3.'
    ],
    practicalTips: 'Este capítulo cierra el módulo aplicando todo lo aprendido: ahora que sabes qué es una neurona, qué hace cada área del cerebro, cómo cambia con la práctica y cómo se comunica con el cuerpo, puedes entender —no solo creer— por qué la meditación tiene efectos reales y medibles. Esta es la base que necesitabas para leer con comprensión un libro de divulgación científica sobre el tema.'
  }
];

// ============================================================
// PREGUNTAS DE TRIVIA (150: 20 MC + 10 V/F por capítulo)
// ============================================================
const questions = [
  // ==========================================================
  // CAPÍTULO 1: La célula que piensa (30 preguntas)
  // ==========================================================
  // Opción múltiple (20)
  { id: 'nt1', moduleId: 'module1', type: 'multiple-choice', question: '¿Aproximadamente cuántas neuronas tiene el cerebro humano?', options: ['86 millones', '86 mil millones', '8.6 billones', '860 mil'], correct: 1, explanation: 'El cerebro humano tiene alrededor de 86 mil millones de neuronas.' },
  { id: 'nt2', moduleId: 'module1', type: 'multiple-choice', question: '¿Cuál es la función principal de las dendritas?', options: ['Enviar el mensaje a otras neuronas', 'Recibir información de otras neuronas', 'Producir energía para la célula', 'Almacenar memoria a largo plazo'], correct: 1, explanation: 'Las dendritas reciben información de otras neuronas.' },
  { id: 'nt3', moduleId: 'module1', type: 'multiple-choice', question: '¿Qué parte de la neurona envía el mensaje hacia adelante, como un cable?', options: ['El soma', 'Las dendritas', 'El axón', 'La sinapsis'], correct: 2, explanation: 'El axón envía el mensaje hacia adelante.' },
  { id: 'nt4', moduleId: 'module1', type: 'multiple-choice', question: '¿Cómo se llama el espacio microscópico entre dos neuronas?', options: ['Axón', 'Sinapsis', 'Soma', 'Dendrita'], correct: 1, explanation: 'El espacio entre dos neuronas se llama sinapsis.' },
  { id: 'nt5', moduleId: 'module1', type: 'multiple-choice', question: '¿Qué es un potencial de acción?', options: ['Un tipo de neurotransmisor', 'El impulso eléctrico que viaja dentro de la neurona', 'El nombre de la sinapsis', 'Una enfermedad neurológica'], correct: 1, explanation: 'El potencial de acción es el impulso eléctrico que viaja dentro de la neurona.' },
  { id: 'nt6', moduleId: 'module1', type: 'multiple-choice', question: 'En la sinapsis, ¿en qué se convierte el impulso eléctrico para cruzar el espacio hacia la siguiente neurona?', options: ['En calor', 'En un mensaje químico (neurotransmisores)', 'En una nueva neurona', 'En ondas sonoras'], correct: 1, explanation: 'El impulso eléctrico se convierte en neurotransmisores para cruzar la sinapsis.' },
  { id: 'nt7', moduleId: 'module1', type: 'multiple-choice', question: '¿Cuál de estos neurotransmisores está más asociado a la motivación y la recompensa?', options: ['Serotonina', 'GABA', 'Dopamina', 'Insulina'], correct: 2, explanation: 'La dopamina está asociada a la motivación y la recompensa.' },
  { id: 'nt8', moduleId: 'module1', type: 'multiple-choice', question: '¿Qué neurotransmisor está más asociado al estado de ánimo?', options: ['Dopamina', 'Serotonina', 'GABA', 'Adrenalina'], correct: 1, explanation: 'La serotonina está asociada al estado de ánimo.' },
  { id: 'nt9', moduleId: 'module1', type: 'multiple-choice', question: '¿Qué neurotransmisor cumple un rol de calma e inhibición en el sistema nervioso?', options: ['GABA', 'Dopamina', 'Serotonina', 'Cortisol'], correct: 0, explanation: 'El GABA tiene un rol de calma e inhibición.' },
  { id: 'nt10', moduleId: 'module1', type: 'multiple-choice', question: '¿Con cuántas otras neuronas puede conectarse, en promedio, una sola neurona a través de sus dendritas?', options: ['Con una sola', 'Con miles', 'Con exactamente 10', 'Con ninguna, actúa sola'], correct: 1, explanation: 'Una neurona puede conectarse con miles de otras neuronas.' },
  { id: 'nt11', moduleId: 'module1', type: 'multiple-choice', question: '¿Qué parte de la neurona procesa la información que llega desde las dendritas?', options: ['El axón', 'El cuerpo celular o soma', 'La sinapsis', 'El neurotransmisor'], correct: 1, explanation: 'El soma procesa la información que llega desde las dendritas.' },
  { id: 'nt12', moduleId: 'module1', type: 'multiple-choice', question: 'Un pensamiento o una emoción es, a nivel biológico:', options: ['La actividad de una sola neurona muy potente', 'La actividad coordinada de redes de neuronas', 'Un proceso que ocurre fuera del cerebro', 'Un evento que no involucra neuronas'], correct: 1, explanation: 'Un pensamiento es la actividad coordinada de redes de neuronas.' },
  { id: 'nt13', moduleId: 'module1', type: 'multiple-choice', question: '¿Qué cruza la sinapsis para "hablarle" a la siguiente neurona?', options: ['El axón completo', 'Los neurotransmisores', 'El soma', 'El potencial de acción sin cambios'], correct: 1, explanation: 'Los neurotransmisores cruzan la sinapsis para comunicarse con la siguiente neurona.' },
  { id: 'nt14', moduleId: 'module1', type: 'multiple-choice', question: '¿Cuál de estas NO es una parte estructural de la neurona mencionada en el capítulo?', options: ['Dendritas', 'Axón', 'Mitocondria motora', 'Soma'], correct: 2, explanation: 'La mitocondria motora no es una parte estructural de la neurona mencionada en el capítulo.' },
  { id: 'nt15', moduleId: 'module1', type: 'multiple-choice', question: 'Si una neurona "dispara", esto significa que:', options: ['Se destruye a sí misma', 'Genera un impulso eléctrico que viaja por el axón', 'Deja de comunicarse con otras neuronas', 'Produce solo calor'], correct: 1, explanation: 'Cuando una neurona "dispara", genera un impulso eléctrico que viaja por el axón.' },
  { id: 'nt16', moduleId: 'module1', type: 'multiple-choice', question: '¿Por qué es incorrecto decir que "una neurona piensa por sí sola"?', options: ['Porque las neuronas no existen', 'Porque el pensamiento requiere la actividad coordinada de muchas neuronas en red', 'Porque solo el cerebelo piensa', 'Porque las neuronas no tienen axón'], correct: 1, explanation: 'El pensamiento requiere la actividad coordinada de muchas neuronas en red.' },
  { id: 'nt17', moduleId: 'module1', type: 'multiple-choice', question: '¿Qué tipo de señal predomina dentro de la neurona (antes de llegar a la sinapsis)?', options: ['Química', 'Eléctrica', 'Hormonal', 'Magnética'], correct: 1, explanation: 'Dentro de la neurona predomina la señal eléctrica.' },
  { id: 'nt18', moduleId: 'module1', type: 'multiple-choice', question: '¿Qué tipo de señal predomina al cruzar la sinapsis hacia la otra neurona?', options: ['Eléctrica', 'Química', 'Sonora', 'Ninguna, no hay transmisión'], correct: 1, explanation: 'Al cruzar la sinapsis, la señal es química (neurotransmisores).' },
  { id: 'nt19', moduleId: 'module1', type: 'multiple-choice', question: 'Entender la neurona y la sinapsis en este capítulo sirve principalmente para:', options: ['Diagnosticar enfermedades', 'Preparar la base para entender la neuroplasticidad más adelante', 'Aprender a programar', 'Reemplazar al Capítulo 2'], correct: 1, explanation: 'Este capítulo prepara la base para entender la neuroplasticidad más adelante.' },
  { id: 'nt20', moduleId: 'module1', type: 'multiple-choice', question: '¿Cuál de estas afirmaciones describe mejor la relación dendrita-axón-sinapsis?', options: ['Las dendritas reciben, el axón envía, la sinapsis es el espacio de paso del mensaje', 'El axón recibe, las dendritas envían, la sinapsis no existe', 'Todas son la misma estructura con nombres distintos', 'La sinapsis reemplaza al axón'], correct: 0, explanation: 'Las dendritas reciben, el axón envía y la sinapsis es el espacio de paso.' },
  // Verdadero o falso (10)
  { id: 'nt21', moduleId: 'module1', type: 'true-false', question: 'Las neuronas se tocan físicamente de forma directa, sin ningún espacio entre ellas.', correct: false, explanation: 'Existe un espacio llamado sinapsis que el mensaje debe cruzar químicamente.' },
  { id: 'nt22', moduleId: 'module1', type: 'true-false', question: 'El cerebro tiene aproximadamente 86 mil millones de neuronas.', correct: true, explanation: 'El cerebro tiene aproximadamente 86 mil millones de neuronas.' },
  { id: 'nt23', moduleId: 'module1', type: 'true-false', question: 'Las dendritas envían información hacia otras neuronas.', correct: false, explanation: 'Las dendritas reciben información; el axón la envía.' },
  { id: 'nt24', moduleId: 'module1', type: 'true-false', question: 'La dopamina está asociada principalmente a la motivación y la recompensa.', correct: true, explanation: 'La dopamina está asociada a la motivación y la recompensa.' },
  { id: 'nt25', moduleId: 'module1', type: 'true-false', question: 'Un pensamiento puede explicarse por la actividad de una única neurona aislada.', correct: false, explanation: 'Un pensamiento requiere redes coordinadas de neuronas.' },
  { id: 'nt26', moduleId: 'module1', type: 'true-false', question: 'El GABA cumple un rol de calma e inhibición en el sistema nervioso.', correct: true, explanation: 'El GABA tiene un rol de calma e inhibición.' },
  { id: 'nt27', moduleId: 'module1', type: 'true-false', question: 'El potencial de acción es un tipo de neurotransmisor.', correct: false, explanation: 'El potencial de acción es el impulso eléctrico dentro de la neurona, no un neurotransmisor.' },
  { id: 'nt28', moduleId: 'module1', type: 'true-false', question: 'Una neurona puede conectarse con miles de otras neuronas.', correct: true, explanation: 'Una neurona puede conectarse con miles de otras neuronas.' },
  { id: 'nt29', moduleId: 'module1', type: 'true-false', question: 'La sinapsis transmite el mensaje mediante electricidad pura, igual que dentro de la neurona.', correct: false, explanation: 'En la sinapsis el mensaje se transmite químicamente, mediante neurotransmisores.' },
  { id: 'nt30', moduleId: 'module1', type: 'true-false', question: 'Entender la neurona es la base necesaria para comprender la neuroplasticidad en capítulos posteriores.', correct: true, explanation: 'Entender la neurona es la base para comprender la neuroplasticidad.' },

  // ==========================================================
  // CAPÍTULO 2: El mapa del cerebro (30 preguntas)
  // ==========================================================
  // Opción múltiple (20)
  { id: 'nt31', moduleId: 'module2', type: 'multiple-choice', question: '¿Dónde se ubica la corteza prefrontal?', options: ['En la parte trasera del cerebro', 'Justo detrás de la frente', 'En el cerebelo', 'En la médula espinal'], correct: 1, explanation: 'La corteza prefrontal está justo detrás de la frente.' },
  { id: 'nt32', moduleId: 'module2', type: 'multiple-choice', question: '¿Cuál es la función principal de la corteza prefrontal?', options: ['Detectar amenazas', 'Tomar decisiones, planificar y frenar impulsos', 'Almacenar recuerdos', 'Controlar el equilibrio'], correct: 1, explanation: 'La corteza prefrontal toma decisiones, planifica y frena impulsos.' },
  { id: 'nt33', moduleId: 'module2', type: 'multiple-choice', question: '¿Qué área funciona como "sistema de alarma" del cerebro?', options: ['Hipocampo', 'Ínsula', 'Amígdala', 'Cerebelo'], correct: 2, explanation: 'La amígdala funciona como sistema de alarma del cerebro.' },
  { id: 'nt34', moduleId: 'module2', type: 'multiple-choice', question: '¿Qué área es responsable de convertir experiencias en recuerdos?', options: ['Amígdala', 'Hipocampo', 'Corteza prefrontal', 'Tronco encefálico'], correct: 1, explanation: 'El hipocampo convierte experiencias en recuerdos.' },
  { id: 'nt35', moduleId: 'module2', type: 'multiple-choice', question: '¿Qué área recibe las señales internas del cuerpo, como los latidos del corazón?', options: ['Ínsula', 'Cerebelo', 'Amígdala', 'Hipocampo'], correct: 0, explanation: 'La ínsula recibe las señales internas del cuerpo.' },
  { id: 'nt36', moduleId: 'module2', type: 'multiple-choice', question: '¿Qué estructuras manejan funciones automáticas como respiración y equilibrio?', options: ['Corteza prefrontal e hipocampo', 'Cerebelo y tronco encefálico', 'Amígdala e ínsula', 'Ninguna, son funciones conscientes'], correct: 1, explanation: 'El cerebelo y el tronco encefálico manejan funciones automáticas.' },
  { id: 'nt37', moduleId: 'module2', type: 'multiple-choice', question: '¿Hasta qué edad aproximada sigue desarrollándose la corteza prefrontal?', options: ['Hasta los 10 años', 'Hasta la adolescencia temprana', 'Hasta mediados de los 20 años', 'Nunca termina de desarrollarse'], correct: 2, explanation: 'La corteza prefrontal se desarrolla hasta mediados de los 20 años.' },
  { id: 'nt38', moduleId: 'module2', type: 'multiple-choice', question: '¿Por qué a veces reaccionas con miedo antes de razonar conscientemente?', options: ['Porque la corteza prefrontal es más rápida que la amígdala', 'Porque la amígdala puede activarse en milisegundos, antes que la corteza prefrontal procese la situación', 'Porque el cerebelo bloquea a la corteza', 'Porque no existe conexión entre amígdala y corteza'], correct: 1, explanation: 'La amígdala puede activarse en milisegundos, antes que la corteza prefrontal procese la situación.' },
  { id: 'nt39', moduleId: 'module2', type: 'multiple-choice', question: '¿Qué hormona, en niveles crónicamente altos, puede dañar el hipocampo?', options: ['Dopamina', 'Cortisol', 'Insulina', 'Melatonina'], correct: 1, explanation: 'El cortisol crónicamente alto puede dañar el hipocampo.' },
  { id: 'nt40', moduleId: 'module2', type: 'multiple-choice', question: '¿Qué nombre recibe la capacidad de sentir el estado interno del propio cuerpo?', options: ['Propiocepción', 'Interocepción', 'Exterocepción', 'Neuroplasticidad'], correct: 1, explanation: 'La interocepción es la capacidad de sentir el estado interno del cuerpo.' },
  { id: 'nt41', moduleId: 'module2', type: 'multiple-choice', question: '¿Cuál de estas áreas está más asociada a la memoria?', options: ['Amígdala', 'Hipocampo', 'Cerebelo', 'Tronco encefálico'], correct: 1, explanation: 'El hipocampo está más asociado a la memoria.' },
  { id: 'nt42', moduleId: 'module2', type: 'multiple-choice', question: 'El cerebelo participa principalmente en:', options: ['Tomar decisiones complejas', 'Coordinación motora y equilibrio', 'Almacenar memoria emocional', 'Detectar amenazas'], correct: 1, explanation: 'El cerebelo participa en coordinación motora y equilibrio.' },
  { id: 'nt43', moduleId: 'module2', type: 'multiple-choice', question: '¿Cuál de estas afirmaciones es correcta sobre el trabajo de las áreas cerebrales?', options: ['Cada área trabaja completamente aislada de las demás', 'Las áreas forman una red interconectada', 'Solo la corteza prefrontal es funcional, el resto es decorativo', 'El cerebro no tiene áreas especializadas'], correct: 1, explanation: 'Las áreas forman una red interconectada.' },
  { id: 'nt44', moduleId: 'module2', type: 'multiple-choice', question: '¿Qué área se relaciona más directamente con el autocontrol y la planificación a futuro?', options: ['Amígdala', 'Corteza prefrontal', 'Cerebelo', 'Tronco encefálico'], correct: 1, explanation: 'La corteza prefrontal se relaciona con autocontrol y planificación.' },
  { id: 'nt45', moduleId: 'module2', type: 'multiple-choice', question: 'La ínsula está ubicada:', options: ['En la superficie externa del cerebro, muy visible', 'En un pliegue profundo del cerebro', 'Fuera del cráneo', 'En la médula espinal'], correct: 1, explanation: 'La ínsula está en un pliegue profundo del cerebro.' },
  { id: 'nt46', moduleId: 'module2', type: 'multiple-choice', question: '¿Qué relación tiene el tronco encefálico con el ritmo cardíaco y la respiración?', options: ['No tiene relación', 'Los regula de forma automática, sin que pienses en ello', 'Solo los regula durante el sueño', 'Los bloquea completamente'], correct: 1, explanation: 'El tronco encefálico regula el ritmo cardíaco y la respiración de forma automática.' },
  { id: 'nt47', moduleId: 'module2', type: 'multiple-choice', question: 'Comprender el "mapa del cerebro" en este capítulo sirve principalmente para:', options: ['Reemplazar el estudio de la neuroplasticidad', 'Tener el vocabulario base para entender los capítulos de cuerpo-cerebro y meditación', 'Diagnosticar enfermedades neurológicas', 'Sustituir al Capítulo 1'], correct: 1, explanation: 'Este capítulo da el vocabulario base para entender los capítulos de cuerpo-cerebro y meditación.' },
  { id: 'nt48', moduleId: 'module2', type: 'multiple-choice', question: '¿Cuál de estas áreas es la MÁS relevante para la interocepción?', options: ['Cerebelo', 'Ínsula', 'Corteza prefrontal', 'Tronco encefálico'], correct: 1, explanation: 'La ínsula es la más relevante para la interocepción.' },
  { id: 'nt49', moduleId: 'module2', type: 'multiple-choice', question: 'Si el hipocampo se ve dañado por estrés crónico, ¿qué función se ve más comprometida?', options: ['El equilibrio', 'La memoria', 'La respiración automática', 'El ritmo cardíaco'], correct: 1, explanation: 'El hipocampo compromete la memoria cuando se daña.' },
  { id: 'nt50', moduleId: 'module2', type: 'multiple-choice', question: '¿Cuál de las siguientes NO es una de las áreas mencionadas en este capítulo?', options: ['Amígdala', 'Ínsula', 'Núcleo accumbens lateral profundo', 'Hipocampo'], correct: 2, explanation: 'El núcleo accumbens lateral profundo no fue mencionado en el capítulo.' },
  // Verdadero o falso (10)
  { id: 'nt51', moduleId: 'module2', type: 'true-false', question: 'La corteza prefrontal es la zona del cerebro que termina de desarrollarse primero.', correct: false, explanation: 'Es la última en terminar de desarrollarse.' },
  { id: 'nt52', moduleId: 'module2', type: 'true-false', question: 'La amígdala puede activarse antes de que la corteza prefrontal procese conscientemente la situación.', correct: true, explanation: 'La amígdala puede activarse en milisegundos.' },
  { id: 'nt53', moduleId: 'module2', type: 'true-false', question: 'El hipocampo es resistente al estrés crónico y no se ve afectado por el cortisol.', correct: false, explanation: 'Es especialmente vulnerable al cortisol sostenido.' },
  { id: 'nt54', moduleId: 'module2', type: 'true-false', question: 'La ínsula participa en la interocepción, es decir, sentir el estado interno del cuerpo.', correct: true, explanation: 'La ínsula participa en la interocepción.' },
  { id: 'nt55', moduleId: 'module2', type: 'true-false', question: 'El cerebelo y el tronco encefálico controlan funciones automáticas como equilibrio y respiración.', correct: true, explanation: 'El cerebelo y el tronco encefálico controlan funciones automáticas.' },
  { id: 'nt56', moduleId: 'module2', type: 'true-false', question: 'Las áreas del cerebro funcionan como compartimentos completamente aislados entre sí.', correct: false, explanation: 'Funcionan como una red interconectada.' },
  { id: 'nt57', moduleId: 'module2', type: 'true-false', question: 'La corteza prefrontal está ubicada detrás de la frente.', correct: true, explanation: 'La corteza prefrontal está justo detrás de la frente.' },
  { id: 'nt58', moduleId: 'module2', type: 'true-false', question: 'El hipocampo es el área principal encargada de detectar amenazas.', correct: false, explanation: 'Esa función corresponde principalmente a la amígdala.' },
  { id: 'nt59', moduleId: 'module2', type: 'true-false', question: 'Entender este mapa de áreas prepara el terreno para los capítulos de cuerpo-cerebro y meditación.', correct: true, explanation: 'Este mapa es la base para los capítulos siguientes.' },
  { id: 'nt60', moduleId: 'module2', type: 'true-false', question: 'La corteza prefrontal termina de desarrollarse completamente antes de los 10 años.', correct: false, explanation: 'Continúa desarrollándose hasta mediados de los 20 años.' },

  // ==========================================================
  // CAPÍTULO 3: Neuroplasticidad (30 preguntas)
  // ==========================================================
  // Opción múltiple (20)
  { id: 'nt61', moduleId: 'module3', type: 'multiple-choice', question: '¿Qué es la neuroplasticidad?', options: ['La incapacidad del cerebro para cambiar', 'La capacidad del cerebro de reorganizarse físicamente con la experiencia', 'Un tipo de neurotransmisor', 'Una enfermedad neurológica'], correct: 1, explanation: 'La neuroplasticidad es la capacidad del cerebro de reorganizarse con la experiencia.' },
  { id: 'nt62', moduleId: 'module3', type: 'multiple-choice', question: '¿Qué ocurre con las conexiones sinápticas cuando repites una actividad?', options: ['Se debilitan siempre', 'Se fortalecen y se vuelven más eficientes', 'Desaparecen por completo', 'No cambian nunca'], correct: 1, explanation: 'Las conexiones sinápticas se fortalecen con la repetición.' },
  { id: 'nt63', moduleId: 'module3', type: 'multiple-choice', question: '¿Qué estudio clásico demostró cambios estructurales en el hipocampo por la práctica repetida?', options: ['Estudio de meditadores tibetanos', 'Estudio de taxistas de Londres', 'Estudio de pilotos de avión', 'Estudio de músicos profesionales solamente'], correct: 1, explanation: 'El estudio de taxistas de Londres demostró cambios estructurales en el hipocampo.' },
  { id: 'nt64', moduleId: 'module3', type: 'multiple-choice', question: '¿Qué área cerebral resultó más grande en los taxistas de Londres del estudio de Maguire et al.?', options: ['Amígdala', 'Hipocampo', 'Cerebelo', 'Corteza prefrontal'], correct: 1, explanation: 'El hipocampo resultó más grande en los taxistas de Londres.' },
  { id: 'nt65', moduleId: 'module3', type: 'multiple-choice', question: 'El principio "úsalo o piérdelo" en neuroplasticidad significa que:', options: ['Las conexiones que no se usan tienden a fortalecerse igual', 'Las conexiones que no se usan tienden a debilitarse', 'Todas las conexiones son permanentes', 'Solo aplica a la infancia'], correct: 1, explanation: 'Las conexiones que no se usan tienden a debilitarse.' },
  { id: 'nt66', moduleId: 'module3', type: 'multiple-choice', question: '¿La neuroplasticidad ocurre solo durante la infancia?', options: ['Sí, exclusivamente', 'No, ocurre durante toda la vida, aunque es más intensa en la infancia', 'Solo después de los 60 años', 'Solo en personas con alguna lesión cerebral'], correct: 1, explanation: 'La neuroplasticidad ocurre durante toda la vida, aunque es más intensa en la infancia.' },
  { id: 'nt67', moduleId: 'module3', type: 'multiple-choice', question: '¿Qué factor es más importante para generar cambios cerebrales duraderos según este capítulo?', options: ['La intensidad de una sola sesión', 'La repetición constante en el tiempo', 'La edad de la persona únicamente', 'El tamaño del cerebro'], correct: 1, explanation: 'La repetición constante en el tiempo es el factor clave para cambios duraderos.' },
  { id: 'nt68', moduleId: 'module3', type: 'multiple-choice', question: '¿Qué concepto del Capítulo 1 está directamente relacionado con la neuroplasticidad?', options: ['La sinapsis y su fortalecimiento', 'El cerebelo', 'La médula espinal', 'El sistema inmune'], correct: 0, explanation: 'La sinapsis y su fortalecimiento están directamente relacionados con la neuroplasticidad.' },
  { id: 'nt69', moduleId: 'module3', type: 'multiple-choice', question: '¿Qué profesión ocupacional se estudió en el ejemplo clásico de plasticidad estructural mencionado?', options: ['Médicos', 'Taxistas', 'Profesores', 'Ingenieros'], correct: 1, explanation: 'El ejemplo clásico es el de taxistas de Londres.' },
  { id: 'nt70', moduleId: 'module3', type: 'multiple-choice', question: '¿Qué tipo de cambio se observó en los taxistas de Londres, más allá de lo funcional?', options: ['Cambios estructurales visibles (mayor tamaño del hipocampo)', 'Ningún cambio detectable', 'Reducción del tamaño de la amígdala', 'Aumento del tamaño del cerebelo únicamente'], correct: 0, explanation: 'Se observaron cambios estructurales visibles en el hipocampo.' },
  { id: 'nt71', moduleId: 'module3', type: 'multiple-choice', question: 'La neuroplasticidad explica científicamente por qué:', options: ['El cerebro nunca cambia', 'Un hábito sostenido en el tiempo puede modificar el cerebro', 'Solo los niños pueden aprender cosas nuevas', 'La meditación no tiene ningún efecto cerebral'], correct: 1, explanation: 'La neuroplasticidad explica por qué un hábito sostenido puede modificar el cerebro.' },
  { id: 'nt72', moduleId: 'module3', type: 'multiple-choice', question: 'Antiguamente, ¿qué se creía sobre el cerebro adulto?', options: ['Que era altamente cambiante', 'Que era fijo e incapaz de cambiar', 'Que crecía indefinidamente', 'Que no tenía neuronas'], correct: 1, explanation: 'Antiguamente se creía que el cerebro adulto era fijo e incapaz de cambiar.' },
  { id: 'nt73', moduleId: 'module3', type: 'multiple-choice', question: '¿Qué tipo de práctica se menciona como ejemplo de actividad que puede generar cambios cerebrales mediante la repetición?', options: ['Dormir sin soñar', 'Aprender un idioma, practicar un deporte o meditar', 'Solo ver televisión', 'Ninguna actividad genera cambios'], correct: 1, explanation: 'Aprender un idioma, practicar un deporte o meditar generan cambios cerebrales con la repetición.' },
  { id: 'nt74', moduleId: 'module3', type: 'multiple-choice', question: 'El Capítulo 3 sirve de "bisagra" hacia los capítulos siguientes porque:', options: ['No tiene relación con el resto del módulo', 'Explica el mecanismo que hace posible los cambios descritos en cuerpo-cerebro y meditación', 'Reemplaza la necesidad de estudiar el cerebro', 'Es el último capítulo del módulo'], correct: 1, explanation: 'El Capítulo 3 explica el mecanismo que hace posibles los cambios en cuerpo-cerebro y meditación.' },
  { id: 'nt75', moduleId: 'module3', type: 'multiple-choice', question: '¿Qué relación existe entre neuroplasticidad y meditación, según se anticipa en este capítulo?', options: ['Ninguna relación', 'La meditación practicada de forma sostenida puede modificar físicamente el cerebro', 'La meditación bloquea la neuroplasticidad', 'Solo la meditación intensa de una vez genera cambios'], correct: 1, explanation: 'La meditación sostenida puede modificar físicamente el cerebro a través de la neuroplasticidad.' },
  { id: 'nt76', moduleId: 'module3', type: 'multiple-choice', question: '¿Quién realizó el estudio de los taxistas de Londres (año 2000)?', options: ['Davidson y colegas', 'Maguire y colegas', 'Ricard y Singer', 'Castellanos'], correct: 1, explanation: 'Maguire y colegas realizaron el estudio de los taxistas de Londres en 2000.' },
  { id: 'nt77', moduleId: 'module3', type: 'multiple-choice', question: '¿Qué tipo de memoria entrenaban intensamente los taxistas de Londres estudiados?', options: ['Memoria de calles y rutas de la ciudad', 'Memoria de rostros', 'Memoria de números telefónicos', 'Memoria musical'], correct: 0, explanation: 'Los taxistas entrenaban memoria de calles y rutas de la ciudad.' },
  { id: 'nt78', moduleId: 'module3', type: 'multiple-choice', question: 'La neuroplasticidad es más intensa en:', options: ['La vejez', 'La infancia', 'Exactamente a los 40 años', 'No varía nunca con la edad'], correct: 1, explanation: 'La neuroplasticidad es más intensa en la infancia.' },
  { id: 'nt79', moduleId: 'module3', type: 'multiple-choice', question: '¿Cuál de estas afirmaciones resume mejor la neuroplasticidad?', options: ['El cerebro es una estructura fija desde el nacimiento', 'El cerebro se reorganiza en respuesta a la experiencia repetida', 'Solo las lesiones cambian el cerebro', 'La plasticidad solo ocurre en el cerebelo'], correct: 1, explanation: 'La neuroplasticidad es la reorganización del cerebro en respuesta a la experiencia repetida.' },
  { id: 'nt80', moduleId: 'module3', type: 'multiple-choice', question: '¿Por qué es relevante entender la neuroplasticidad antes de estudiar la meditación (Capítulo 5)?', options: ['Porque no tiene relación con la meditación', 'Porque explica el mecanismo por el cual la meditación sostenida puede cambiar el cerebro', 'Porque reemplaza el estudio de la meditación', 'Porque la meditación no involucra al cerebro'], correct: 1, explanation: 'La neuroplasticidad explica el mecanismo por el cual la meditación sostenida puede cambiar el cerebro.' },
  // Verdadero o falso (10)
  { id: 'nt81', moduleId: 'module3', type: 'true-false', question: 'El cerebro adulto es completamente fijo y no puede cambiar.', correct: false, explanation: 'El cerebro se reorganiza mediante neuroplasticidad durante toda la vida.' },
  { id: 'nt82', moduleId: 'module3', type: 'true-false', question: 'La repetición de una actividad puede fortalecer las conexiones sinápticas involucradas.', correct: true, explanation: 'La repetición fortalece las conexiones sinápticas.' },
  { id: 'nt83', moduleId: 'module3', type: 'true-false', question: 'El estudio de los taxistas de Londres mostró un hipocampo más grande de lo normal.', correct: true, explanation: 'El hipocampo de los taxistas de Londres era más grande de lo normal.' },
  { id: 'nt84', moduleId: 'module3', type: 'true-false', question: 'La neuroplasticidad ocurre exclusivamente durante la infancia.', correct: false, explanation: 'Ocurre durante toda la vida, aunque es más intensa en la infancia.' },
  { id: 'nt85', moduleId: 'module3', type: 'true-false', question: 'El principio "úsalo o piérdelo" indica que las conexiones no usadas tienden a debilitarse.', correct: true, explanation: 'Las conexiones no usadas tienden a debilitarse.' },
  { id: 'nt86', moduleId: 'module3', type: 'true-false', question: 'La intensidad de una sola sesión es más importante que la repetición constante para generar cambios cerebrales duraderos.', correct: false, explanation: 'La repetición constante en el tiempo es el factor clave.' },
  { id: 'nt87', moduleId: 'module3', type: 'true-false', question: 'El estudio de Maguire et al. (2000) es una de las evidencias más citadas de plasticidad estructural.', correct: true, explanation: 'El estudio de Maguire et al. es una evidencia clave de plasticidad estructural.' },
  { id: 'nt88', moduleId: 'module3', type: 'true-false', question: 'La neuroplasticidad no tiene relación con por qué la meditación puede cambiar el cerebro.', correct: false, explanation: 'La neuroplasticidad es el mecanismo que explica cómo la meditación cambia el cerebro.' },
  { id: 'nt89', moduleId: 'module3', type: 'true-false', question: 'Los taxistas de Londres fueron estudiados por memorizar rutas y calles de la ciudad.', correct: true, explanation: 'Los taxistas fueron estudiados por su memoria de rutas y calles de Londres.' },
  { id: 'nt90', moduleId: 'module3', type: 'true-false', question: 'Comprender la neuroplasticidad no aporta nada para entender los capítulos siguientes del módulo.', correct: false, explanation: 'Es la bisagra hacia los capítulos de cuerpo-cerebro y meditación.' },

  // ==========================================================
  // CAPÍTULO 4: Cuerpo-cerebro (30 preguntas)
  // ==========================================================
  // Opción múltiple (20)
  { id: 'nt91', moduleId: 'module4', type: 'multiple-choice', question: '¿Qué es la interocepción?', options: ['La capacidad de ver colores', 'La capacidad de percibir señales internas del cuerpo', 'Un tipo de neurotransmisor', 'La memoria de largo plazo'], correct: 1, explanation: 'La interocepción es la capacidad de percibir señales internas del cuerpo.' },
  { id: 'nt92', moduleId: 'module4', type: 'multiple-choice', question: '¿Qué estructura cerebral es central en el procesamiento de la interocepción?', options: ['Cerebelo', 'Ínsula', 'Tronco encefálico', 'Hipocampo'], correct: 1, explanation: 'La ínsula es central en el procesamiento de la interocepción.' },
  { id: 'nt93', moduleId: 'module4', type: 'multiple-choice', question: '¿Qué efecto tiene la respiración nasal sobre el cerebro, según este capítulo?', options: ['Ninguno', 'Influye en zonas relacionadas con memoria y emoción', 'Solo afecta al sistema digestivo', 'Bloquea completamente la amígdala'], correct: 1, explanation: 'La respiración nasal influye en zonas relacionadas con memoria y emoción.' },
  { id: 'nt94', moduleId: 'module4', type: 'multiple-choice', question: '¿Qué se entiende por "eje intestino-cerebro"?', options: ['Una vía de comunicación bidireccional entre intestino y cerebro', 'Un músculo del abdomen', 'Una parte del sistema óseo', 'Un tipo de neurona exclusiva del intestino'], correct: 0, explanation: 'El eje intestino-cerebro es una vía de comunicación bidireccional entre intestino y cerebro.' },
  { id: 'nt95', moduleId: 'module4', type: 'multiple-choice', question: '¿Qué alberga el intestino que se comunica con el cerebro?', options: ['La microbiota (microorganismos)', 'Solo tejido muscular', 'Neuronas motoras exclusivamente', 'Ninguna sustancia relevante'], correct: 0, explanation: 'El intestino alberga la microbiota, que se comunica con el cerebro.' },
  { id: 'nt96', moduleId: 'module4', type: 'multiple-choice', question: '¿Qué aspecto del latido cardíaco es relevante para el estado del sistema nervioso, más allá de la frecuencia simple?', options: ['El color de la sangre', 'La variabilidad del latido cardíaco', 'El tamaño del corazón', 'La temperatura corporal'], correct: 1, explanation: 'La variabilidad del latido cardíaco es relevante para el estado del sistema nervioso.' },
  { id: 'nt97', moduleId: 'module4', type: 'multiple-choice', question: 'La comunicación cuerpo-cerebro descrita en este capítulo es:', options: ['Unidireccional, solo del cerebro al cuerpo', 'Bidireccional', 'Inexistente', 'Solo teórica, sin evidencia'], correct: 1, explanation: 'La comunicación cuerpo-cerebro es bidireccional.' },
  { id: 'nt98', moduleId: 'module4', type: 'multiple-choice', question: '¿Qué práctica se menciona como ejemplo de aplicación directa de este capítulo?', options: ['Memorizar listas de palabras', 'Respiración consciente', 'Resolución de ecuaciones matemáticas', 'Aprender idiomas'], correct: 1, explanation: 'La respiración consciente se menciona como aplicación directa.' },
  { id: 'nt99', moduleId: 'module4', type: 'multiple-choice', question: '¿Qué relación tiene el eje intestino-cerebro con el estado de ánimo?', options: ['Ninguna relación', 'Puede influir en el estado de ánimo', 'Solo afecta la digestión, nunca el ánimo', 'Reemplaza completamente a la amígdala'], correct: 1, explanation: 'El eje intestino-cerebro puede influir en el estado de ánimo.' },
  { id: 'nt100', moduleId: 'module4', type: 'multiple-choice', question: '¿Qué área del cerebro vista en el Capítulo 2 vuelve a ser protagonista en este capítulo?', options: ['Cerebelo', 'Ínsula', 'Tronco encefálico', 'Corteza motora'], correct: 1, explanation: 'La ínsula vuelve a ser protagonista en este capítulo.' },
  { id: 'nt101', moduleId: 'module4', type: 'multiple-choice', question: '¿Por qué la ínsula es clave para la interocepción?', options: ['Porque procesa las señales corporales internas', 'Porque controla el equilibrio', 'Porque almacena recuerdos a largo plazo', 'Porque genera el impulso eléctrico neuronal'], correct: 0, explanation: 'La ínsula procesa las señales corporales internas.' },
  { id: 'nt102', moduleId: 'module4', type: 'multiple-choice', question: 'El concepto de "eje intestino-cerebro" implica que:', options: ['El intestino no tiene ninguna influencia sobre el cerebro', 'El cerebro y el intestino se influyen mutuamente', 'Solo el cerebro controla al intestino, sin retroalimentación', 'Es un concepto sin evidencia científica'], correct: 1, explanation: 'El cerebro y el intestino se influyen mutuamente.' },
  { id: 'nt103', moduleId: 'module4', type: 'multiple-choice', question: '¿Qué conecta este capítulo con el Capítulo 5 (meditación)?', options: ['No tiene ninguna conexión', 'Gran parte de la meditación entrena justamente la comunicación cuerpo-cerebro', 'El Capítulo 5 elimina lo aprendido aquí', 'Son temas completamente independientes'], correct: 1, explanation: 'La meditación entrena la comunicación cuerpo-cerebro.' },
  { id: 'nt104', moduleId: 'module4', type: 'multiple-choice', question: 'La respiración consciente puede influir en el estado mental porque:', options: ['Existe una vía biológica real entre respiración y circuitos cerebrales', 'Es solo un efecto placebo sin base biológica', 'Cambia el color de las neuronas', 'No tiene relación con el cerebro'], correct: 0, explanation: 'Existe una vía biológica real entre respiración y circuitos cerebrales.' },
  { id: 'nt105', moduleId: 'module4', type: 'multiple-choice', question: '¿Qué nervio suele mencionarse como vía de comunicación entre cuerpo y cerebro en el contexto de interocepción?', options: ['Nervio óptico', 'Nervio vago', 'Nervio facial', 'Nervio ciático'], correct: 1, explanation: 'El nervio vago es una vía de comunicación entre cuerpo y cerebro.' },
  { id: 'nt106', moduleId: 'module4', type: 'multiple-choice', question: '¿Cuál de estas NO es una señal interoceptiva mencionada en el capítulo?', options: ['Latidos del corazón', 'Tensión muscular', 'Sensación de hambre', 'Longitud de onda de la luz'], correct: 3, explanation: 'La longitud de onda de la luz no es una señal interoceptiva.' },
  { id: 'nt107', moduleId: 'module4', type: 'multiple-choice', question: 'Entender el eje intestino-cerebro ayuda a comprender por qué:', options: ['El estado de ánimo puede estar influido por factores digestivos', 'El cerebro no depende de ningún otro órgano', 'La memoria depende solo del hipocampo', 'La respiración no tiene relación con el cerebro'], correct: 0, explanation: 'El estado de ánimo puede estar influido por factores digestivos.' },
  { id: 'nt108', moduleId: 'module4', type: 'multiple-choice', question: 'El mensaje central de este capítulo es que:', options: ['El cerebro funciona completamente aislado del cuerpo', 'El cerebro está en comunicación constante con el resto del cuerpo', 'El cuerpo no influye nunca en el estado mental', 'Solo la corteza prefrontal importa para el bienestar'], correct: 1, explanation: 'El cerebro está en comunicación constante con el resto del cuerpo.' },
  { id: 'nt109', moduleId: 'module4', type: 'multiple-choice', question: '¿Qué tipo de comunicación (eléctrica, química o ambas) puede darse entre intestino y cerebro?', options: ['Solo eléctrica', 'Solo química', 'Ambas: nerviosa y química', 'Ninguna, no existe comunicación'], correct: 2, explanation: 'La comunicación entre intestino y cerebro es tanto nerviosa como química.' },
  { id: 'nt110', moduleId: 'module4', type: 'multiple-choice', question: '¿Por qué se dice que "el cerebro no está solo" en el título de este capítulo?', options: ['Porque siempre hay otra persona presente', 'Porque el cerebro depende de y se comunica con el resto del cuerpo', 'Porque el cerebro tiene dos hemisferios', 'Porque hay más de una amígdala'], correct: 1, explanation: 'El cerebro depende de y se comunica con el resto del cuerpo.' },
  // Verdadero o falso (10)
  { id: 'nt111', moduleId: 'module4', type: 'true-false', question: 'La interocepción es la capacidad de percibir señales internas del propio cuerpo.', correct: true, explanation: 'La interocepción es la capacidad de percibir señales internas del cuerpo.' },
  { id: 'nt112', moduleId: 'module4', type: 'true-false', question: 'La ínsula no tiene relación con la interocepción.', correct: false, explanation: 'La ínsula es la estructura central en el procesamiento de la interocepción.' },
  { id: 'nt113', moduleId: 'module4', type: 'true-false', question: 'La forma de respirar puede influir en circuitos cerebrales de memoria y emoción.', correct: true, explanation: 'La respiración influye en circuitos cerebrales de memoria y emoción.' },
  { id: 'nt114', moduleId: 'module4', type: 'true-false', question: 'El eje intestino-cerebro es una comunicación unidireccional, solo del cerebro hacia el intestino.', correct: false, explanation: 'El eje intestino-cerebro es bidireccional.' },
  { id: 'nt115', moduleId: 'module4', type: 'true-false', question: 'La variabilidad del latido cardíaco se relaciona con el estado del sistema nervioso.', correct: true, explanation: 'La variabilidad del latido cardíaco se relaciona con el estado del sistema nervioso.' },
  { id: 'nt116', moduleId: 'module4', type: 'true-false', question: 'La microbiota intestinal no tiene ninguna influencia sobre el cerebro.', correct: false, explanation: 'La microbiota intestinal se comunica con el cerebro y puede influir en el estado de ánimo.' },
  { id: 'nt117', moduleId: 'module4', type: 'true-false', question: 'Este capítulo no tiene relación con el capítulo de meditación que sigue.', correct: false, explanation: 'La meditación entrena justamente esta comunicación cuerpo-cerebro.' },
  { id: 'nt118', moduleId: 'module4', type: 'true-false', question: 'La respiración consciente tiene una base biológica real, no es solo una idea motivacional.', correct: true, explanation: 'La respiración consciente tiene una base biológica real.' },
  { id: 'nt119', moduleId: 'module4', type: 'true-false', question: 'El cerebro funciona de manera completamente aislada del resto del cuerpo.', correct: false, explanation: 'El cerebro está en comunicación constante con el cuerpo.' },
  { id: 'nt120', moduleId: 'module4', type: 'true-false', question: 'El nervio vago es una de las vías mencionadas en la comunicación cuerpo-cerebro.', correct: true, explanation: 'El nervio vago es una vía de comunicación cuerpo-cerebro.' },

  // ==========================================================
  // CAPÍTULO 5: Qué le pasa al cerebro cuando meditas (30 preguntas)
  // ==========================================================
  // Opción múltiple (20)
  { id: 'nt121', moduleId: 'module5', type: 'multiple-choice', question: '¿Qué área del cerebro muestra menor activación ante estímulos negativos en meditadores con más práctica?', options: ['Hipocampo', 'Amígdala', 'Cerebelo', 'Tronco encefálico'], correct: 1, explanation: 'La amígdala muestra menor activación en meditadores con más práctica.' },
  { id: 'nt122', moduleId: 'module5', type: 'multiple-choice', question: '¿Qué significa que los meditadores expertos tengan "mayor eficiencia atencional"?', options: ['Necesitan más esfuerzo cerebral para mantener la atención', 'Logran el mismo resultado atencional con menos esfuerzo cerebral', 'Pierden la capacidad de prestar atención', 'No tiene relación con el esfuerzo cerebral'], correct: 1, explanation: 'Los meditadores expertos logran el mismo resultado atencional con menos esfuerzo cerebral.' },
  { id: 'nt123', moduleId: 'module5', type: 'multiple-choice', question: '¿Qué tipo de ondas cerebrales se han registrado en sincronía inusual en meditadores de larga trayectoria?', options: ['Ondas delta', 'Ondas gamma', 'Ondas de radio', 'Ondas sonoras'], correct: 1, explanation: 'Se han registrado ondas gamma en sincronía inusual en meditadores de larga trayectoria.' },
  { id: 'nt124', moduleId: 'module5', type: 'multiple-choice', question: '¿Con qué población se ha realizado gran parte de la investigación científica sobre meditación mencionada en este capítulo?', options: ['Niños sin entrenamiento', 'Meditadores budistas experimentados', 'Personas con insomnio', 'Atletas de alto rendimiento'], correct: 1, explanation: 'La investigación se ha realizado principalmente con meditadores budistas experimentados.' },
  { id: 'nt125', moduleId: 'module5', type: 'multiple-choice', question: 'Según este capítulo, la meditación es principalmente:', options: ['Un fenómeno místico sin explicación científica', 'Una forma de entrenamiento mental sujeta a principios de neuroplasticidad', 'Un evento que ocurre una sola vez y cambia el cerebro para siempre', 'Algo que no involucra al cerebro'], correct: 1, explanation: 'La meditación es una forma de entrenamiento mental sujeta a principios de neuroplasticidad.' },
  { id: 'nt126', moduleId: 'module5', type: 'multiple-choice', question: '¿Qué concepto del Capítulo 3 es clave para entender por qué la meditación cambia el cerebro?', options: ['La sinapsis únicamente', 'La neuroplasticidad', 'El cerebelo', 'La corteza motora'], correct: 1, explanation: 'La neuroplasticidad es clave para entender por qué la meditación cambia el cerebro.' },
  { id: 'nt127', moduleId: 'module5', type: 'multiple-choice', question: '¿Qué relación existe entre la práctica sostenida de meditación y la reactividad amigdalar?', options: ['No hay relación', 'La práctica sostenida se asocia con menor reactividad ante estímulos negativos', 'La meditación aumenta siempre la reactividad de la amígdala', 'Solo afecta al cerebelo'], correct: 1, explanation: 'La práctica sostenida de meditación se asocia con menor reactividad de la amígdala.' },
  { id: 'nt128', moduleId: 'module5', type: 'multiple-choice', question: '¿Este capítulo describe la meditación como un efecto:', options: ['Mágico e inmediato', 'Medible y gradual, propio de un entrenamiento repetido', 'Sin ninguna base científica', 'Exclusivo de una sola sesión de práctica'], correct: 1, explanation: 'La meditación es un efecto medible y gradual, propio de un entrenamiento repetido.' },
  { id: 'nt129', moduleId: 'module5', type: 'multiple-choice', question: '¿Qué área, vista en el Capítulo 2, es central para entender la regulación emocional en meditadores?', options: ['Amígdala', 'Cerebelo', 'Bulbo raquídeo', 'Núcleo caudado'], correct: 0, explanation: 'La amígdala es central para entender la regulación emocional en meditadores.' },
  { id: 'nt130', moduleId: 'module5', type: 'multiple-choice', question: 'La colaboración entre neurocientíficos y practicantes contemplativos budistas ha permitido:', options: ['Invalidar los estudios de meditación', 'Estudiar de forma directa los efectos cerebrales de la práctica sostenida', 'Eliminar la necesidad de estudiar el cerebro', 'Demostrar que la meditación no tiene efectos'], correct: 1, explanation: 'Ha permitido estudiar de forma directa los efectos cerebrales de la práctica sostenida.' },
  { id: 'nt131', moduleId: 'module5', type: 'multiple-choice', question: '¿Qué capítulo previo explica el mecanismo por el cual la práctica repetida de meditación puede cambiar el cerebro?', options: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3 (neuroplasticidad)', 'Ninguno'], correct: 2, explanation: 'El Capítulo 3 (neuroplasticidad) explica el mecanismo por el cual la práctica repetida cambia el cerebro.' },
  { id: 'nt132', moduleId: 'module5', type: 'multiple-choice', question: '¿Qué capítulo previo aporta la base para entender por qué la respiración consciente, usada en meditación, afecta al cerebro?', options: ['Capítulo 1', 'Capítulo 4 (cuerpo-cerebro)', 'Capítulo 2 únicamente', 'Ninguno'], correct: 1, explanation: 'El Capítulo 4 (cuerpo-cerebro) aporta la base para entender por qué la respiración consciente afecta al cerebro.' },
  { id: 'nt133', moduleId: 'module5', type: 'multiple-choice', question: 'Según los hallazgos descritos, ¿la eficiencia atencional en meditadores mejora con...?', options: ['Una sola sesión de meditación', 'Las horas acumuladas de práctica', 'La edad únicamente, sin relación con la práctica', 'No mejora nunca'], correct: 1, explanation: 'La eficiencia atencional mejora con las horas acumuladas de práctica.' },
  { id: 'nt134', moduleId: 'module5', type: 'multiple-choice', question: '¿Qué tipo de evidencia se usa para sustentar los hallazgos de este capítulo?', options: ['Opiniones sin respaldo', 'Estudios con técnicas como fMRI y EEG en meditadores', 'Solo testimonios anecdóticos', 'Ninguna evidencia científica'], correct: 1, explanation: 'Se usan estudios con técnicas como fMRI y EEG en meditadores.' },
  { id: 'nt135', moduleId: 'module5', type: 'multiple-choice', question: 'El objetivo final de este capítulo, y del módulo completo, es que el usuario:', options: ['Memorice nombres de neurotransmisores sin comprenderlos', 'Entienda, con base científica, qué le pasa al cerebro cuando medita', 'Deje de practicar meditación', 'Sustituya la meditación por otra práctica'], correct: 1, explanation: 'El objetivo es que el usuario entienda qué le pasa al cerebro cuando medita.' },
  { id: 'nt136', moduleId: 'module5', type: 'multiple-choice', question: '¿Qué NO describe correctamente los hallazgos sobre meditación y amígdala?', options: ['Menor reactividad ante estímulos negativos con más práctica', 'Mayor reactividad ante estímulos negativos con más práctica', 'Relación entre horas de práctica y respuesta amigdalar', 'Estudios con meditadores experimentados'], correct: 1, explanation: 'No describe correctamente que haya mayor reactividad con más práctica.' },
  { id: 'nt137', moduleId: 'module5', type: 'multiple-choice', question: 'La sincronía gamma registrada en meditadores expertos es:', options: ['Común en cualquier persona sin entrenamiento', 'Un patrón inusual, más presente en meditadores de larga trayectoria', 'Un artefacto sin ningún significado', 'Exclusiva de personas con insomnio'], correct: 1, explanation: 'La sincronía gamma es un patrón inusual en meditadores de larga trayectoria.' },
  { id: 'nt138', moduleId: 'module5', type: 'multiple-choice', question: 'Este capítulo cierra el módulo aplicando:', options: ['Solo el contenido del Capítulo 1', 'La integración de todos los capítulos anteriores (neurona, áreas, plasticidad, cuerpo-cerebro)', 'Ningún contenido previo', 'Solo conceptos de anatomía ósea'], correct: 1, explanation: 'Este capítulo integra todos los capítulos anteriores.' },
  { id: 'nt139', moduleId: 'module5', type: 'multiple-choice', question: '¿Qué papel cumple la corteza prefrontal en la regulación durante la práctica meditativa, según lo visto en capítulos anteriores?', options: ['Ninguno', 'Participa en el autocontrol y la regulación de impulsos, relevante en la práctica atencional', 'Solo controla el equilibrio', 'Es irrelevante para la meditación'], correct: 1, explanation: 'La corteza prefrontal participa en el autocontrol y la regulación de impulsos.' },
  { id: 'nt140', moduleId: 'module5', type: 'multiple-choice', question: 'Al terminar este capítulo, el usuario debería poder:', options: ['Solo memorizar nombres sin conexión entre sí', 'Comprender con lógica científica encadenada por qué la meditación afecta al cerebro', 'Ignorar todo lo aprendido en capítulos previos', 'Ninguna de las anteriores'], correct: 1, explanation: 'El usuario debería comprender por qué la meditación afecta al cerebro con lógica científica.' },
  // Verdadero o falso (10)
  { id: 'nt141', moduleId: 'module5', type: 'true-false', question: 'La práctica sostenida de meditación se asocia con menor reactividad de la amígdala ante estímulos negativos.', correct: true, explanation: 'La meditación sostenida se asocia con menor reactividad de la amígdala.' },
  { id: 'nt142', moduleId: 'module5', type: 'true-false', question: 'Los meditadores expertos necesitan más esfuerzo cerebral para mantener la atención que los principiantes.', correct: false, explanation: 'Los meditadores expertos muestran mayor eficiencia, con menos esfuerzo.' },
  { id: 'nt143', moduleId: 'module5', type: 'true-false', question: 'Se han registrado patrones de sincronía gamma inusuales en meditadores de larga trayectoria.', correct: true, explanation: 'Se han registrado patrones de sincronía gamma inusuales en meditadores de larga trayectoria.' },
  { id: 'nt144', moduleId: 'module5', type: 'true-false', question: 'La meditación, según este capítulo, es un fenómeno sin ninguna base científica.', correct: false, explanation: 'Está sustentada por estudios con fMRI y EEG.' },
  { id: 'nt145', moduleId: 'module5', type: 'true-false', question: 'Gran parte de la investigación mencionada se realizó con meditadores budistas experimentados.', correct: true, explanation: 'La investigación se realizó con meditadores budistas experimentados.' },
  { id: 'nt146', moduleId: 'module5', type: 'true-false', question: 'La neuroplasticidad (Capítulo 3) es irrelevante para entender los efectos de la meditación.', correct: false, explanation: 'La neuroplasticidad es el mecanismo central que explica los efectos de la meditación.' },
  { id: 'nt147', moduleId: 'module5', type: 'true-false', question: 'Los efectos cerebrales de la meditación descritos en este capítulo son inmediatos y no requieren práctica sostenida.', correct: false, explanation: 'Son graduales y se asocian con la práctica sostenida.' },
  { id: 'nt148', moduleId: 'module5', type: 'true-false', question: 'La respiración consciente, vista en el Capítulo 4, se relaciona con lo que ocurre durante la meditación.', correct: true, explanation: 'La respiración consciente se relaciona con lo que ocurre durante la meditación.' },
  { id: 'nt149', moduleId: 'module5', type: 'true-false', question: 'Este capítulo integra conceptos de todos los capítulos anteriores del módulo.', correct: true, explanation: 'Este capítulo integra conceptos de todos los capítulos anteriores.' },
  { id: 'nt150', moduleId: 'module5', type: 'true-false', question: 'No existe ninguna evidencia científica que vincule la práctica meditativa con cambios medibles en el cerebro.', correct: false, explanation: 'Existen estudios con fMRI y EEG que sustentan estos hallazgos.' }
];

// ============================================================
// FUNCIÓN PRINCIPAL PARA SUBIR DATOS
// ============================================================
export default function SeedNeuro() {
  const handleSeed = async () => {
    try {
      // Subir capítulos
      for (const module of modules) {
        await setDoc(doc(db, 'neuroModules', module.id), module);
        console.log(`✅ Subido capítulo: ${module.title}`);
      }

      // Subir preguntas
      for (const q of questions) {
        await setDoc(doc(db, 'neuroTrivia', q.id), q);
      }
      console.log(`✅ Subidas ${questions.length} preguntas`);

      alert('🎉 Datos de Neurociencias subidos correctamente.');
    } catch (error) {
      console.error('❌ Error:', error);
      alert('❌ Error al subir datos. Revisa la consola.');
    }
  };

  return (
    <button
      onClick={handleSeed}
      style={{
        padding: '12px 24px',
        background: '#6C63FF',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '1rem',
        marginBottom: '20px'
      }}
    >
      🧠 Subir Neurociencias
    </button>
  );
}